from __future__ import annotations

import argparse
import sys
from pathlib import Path


REQUIRED_FILES = (
    "README.md",
    "ROADMAP.md",
    "CONTRIBUTING.md",
    "CHANGELOG.md",
    "LICENSE",
    "AGENTS.md",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
    ".gitattributes",
    ".gitignore",
    "docs/development/AI-00-baseline-audit.md",
    "docs/development/handoffs/AI-00-final-handoff.md",
    "docs/architecture/domain-contract.md",
    "docs/architecture/scope-boundaries.md",
    "docs/architecture/prohibited-capabilities.md",
    "docs/development/handoffs/AI-01-final-handoff.md",
    "docs/architecture/master-taxonomy-v1.md",
    "docs/architecture/taxonomy-index.yaml",
    "docs/development/handoffs/AI-02-final-handoff.md",
    "docs/architecture/sensitivity-model.md",
    "docs/architecture/authority-routing.md",
    "docs/architecture/intrusive-task-gate.md",
    "docs/architecture/certification-boundaries.md",
    "docs/development/handoffs/AI-03-final-handoff.md",
    "docs/standards/skill-authoring-standard.md",
    "docs/standards/skill-naming-standard.md",
    "docs/standards/output-contract-standard.md",
    "docs/development/handoffs/AI-04-final-handoff.md",
    "docs/standards/research-and-evidence-standard.md",
    "docs/standards/regulatory-source-standard.md",
    "docs/standards/source-freshness-standard.md",
    "docs/development/handoffs/AI-05-final-handoff.md",
    "docs/standards/testing-standard.md",
    "docs/standards/evaluation-standard.md",
    "tests/validation-scenarios.json",
    "tests/evaluation-rubric.json",
    "docs/development/handoffs/AI-06-final-handoff.md",
    "docs/foundations/foundation-catalog.md",
    "docs/foundations/professional-vocabulary.md",
    "docs/foundations/shared-schemas.md",
    "docs/foundations/report-structure-contracts.md",
    "docs/foundations/foundation-consumer-map.json",
    "docs/development/handoffs/AI-07-final-handoff.md",
    "tests/reference-skills/AI-08-reference-scenarios.json",
    "docs/development/handoffs/AI-08-final-handoff.md",
    "tests/reference-skills/AI-09-professional-core-scenarios.json",
    "docs/development/handoffs/AI-09-final-handoff.md",
    "tests/reference-skills/AI-10-authority-compliance-scenarios.json",
    "docs/development/handoffs/AI-10-final-handoff.md",
    "tests/reference-skills/AI-11-case-management-scenarios.json",
    "docs/development/handoffs/AI-11-final-handoff.md",
    "tests/reference-skills/AI-12-research-osint-scenarios.json",
    "docs/development/handoffs/AI-12-final-handoff.md",
    "tests/reference-skills/AI-13-entity-analysis-scenarios.json",
    "docs/development/handoffs/AI-13-final-handoff.md",
    "tests/reference-skills/AI-14-interviewing-scenarios.json",
    "docs/development/handoffs/AI-14-final-handoff.md",
    "tests/reference-skills/AI-15-evidence-scenarios.json",
    "docs/development/handoffs/AI-15-final-handoff.md",
    "tests/reference-skills/AI-16-investigative-analysis-scenarios.json",
    "docs/development/handoffs/AI-16-final-handoff.md",
    "tests/reference-skills/AI-17-reporting-scenarios.json",
    "docs/development/handoffs/AI-17-final-handoff.md",
    "tests/reference-skills/AI-18-observation-governance-scenarios.json",
    "docs/development/handoffs/AI-18-final-handoff.md",
    "tests/reference-skills/AI-19-workplace-investigations-scenarios.json",
    "docs/development/handoffs/AI-19-final-handoff.md",
    "tests/reference-skills/AI-20-screening-due-diligence-scenarios.json",
    "docs/development/handoffs/AI-20-final-handoff.md",
    "tests/reference-skills/AI-21-security-operations-scenarios.json",
    "docs/development/handoffs/AI-21-final-handoff.md",
    "tests/reference-skills/AI-22-incident-communication-scenarios.json",
    "docs/development/handoffs/AI-22-final-handoff.md",
    "tests/reference-skills/AI-23-physical-security-scenarios.json",
    "docs/development/handoffs/AI-23-final-handoff.md",
    "tests/reference-skills/AI-24-security-systems-scenarios.json",
    "docs/development/handoffs/AI-24-final-handoff.md",
    "tests/reference-skills/AI-25-loss-prevention-scenarios.json",
    "docs/development/handoffs/AI-25-final-handoff.md",
    "tests/reference-skills/AI-26-program-management-scenarios.json",
    "docs/development/handoffs/AI-26-final-handoff.md",
    "specializations/canada/federal/README.md",
    "specializations/canada/federal/source-log.yaml",
    "specializations/canada/federal/privacy-and-information-handling.md",
    "specializations/canada/federal/criminal-law-interaction.md",
    "specializations/canada/federal/evidence-and-records.md",
    "specializations/canada/federal/human-rights-and-federal-organizations.md",
    "specializations/canada/federal/routing-boundaries.md",
    "tests/regulatory/AI-27-canada-federal-specialization.json",
    "docs/development/handoffs/AI-27-final-handoff.md",
    "scripts/validate-all.ps1",
    "scripts/validate-docs.py",
    "scripts/validate-taxonomy.py",
    "scripts/generate-taxonomy.py",
    "scripts/validate-routing.py",
    "scripts/validate-standards.py",
    "scripts/validate-tests.py",
    "scripts/validate-foundations.py",
    "scripts/validate-skills.py",
    "scripts/validate-specializations.py",
)

REQUIRED_TOKENS = {
    "ROADMAP.md": (
        "AgentInvestigate Development Roadmap",
        "Roadmap version: 0.1",
        "AGENTINVESTIGATE_DEVELOPMENT_ROADMAP_V0_1_READY",
    ),
    "docs/development/AI-00-baseline-audit.md": (
        "AGENTINVESTIGATE_AI_00_BASELINE_READY",
        "Source handling rule applied",
        "No skill folders, skillsets, specializations, shared assets, fixtures, or future-wave architecture files were created.",
    ),
    "docs/development/handoffs/AI-00-final-handoff.md": (
        "AGENTINVESTIGATE_AI_00_BASELINE_READY",
        "AI-01: Domain & Scope Contract.",
    ),
    "docs/architecture/domain-contract.md": (
        "AGENTINVESTIGATE_AI_01_DOMAIN_CONTRACT_READY",
        "Private Investigation",
        "Private Security",
        "Taxonomy Family Mapping",
        "Every roadmap taxonomy family maps cleanly to the domain contract.",
    ),
    "docs/architecture/scope-boundaries.md": (
        "AGENTINVESTIGATE_AI_01_DOMAIN_CONTRACT_READY",
        "In Scope",
        "Out Of Scope",
        "Required Gates",
        "Acceptance Criteria",
    ),
    "docs/architecture/prohibited-capabilities.md": (
        "AGENTINVESTIGATE_AI_01_DOMAIN_CONTRACT_READY",
        "Absolute Exclusions",
        "Response And Routing Rules",
        "Design Constraints For Future Skills",
    ),
    "docs/development/handoffs/AI-01-final-handoff.md": (
        "AGENTINVESTIGATE_AI_01_DOMAIN_CONTRACT_READY",
        "AI-02: Master Taxonomy Integration.",
    ),
    "docs/architecture/master-taxonomy-v1.md": (
        "AGENTINVESTIGATE_AI_02_MASTER_TAXONOMY_READY",
        "`docs/architecture/taxonomy-index.yaml` is the canonical taxonomy source.",
        "Exactly one canonical taxonomy source exists: docs/architecture/taxonomy-index.yaml",
    ),
    "docs/architecture/taxonomy-index.yaml": (
        "AGENTINVESTIGATE_AI_02_MASTER_TAXONOMY_READY",
        "AgentInvestigate Master Taxonomy v1.0",
        "\"skills\": 212",
    ),
    "docs/development/handoffs/AI-02-final-handoff.md": (
        "AGENTINVESTIGATE_AI_02_MASTER_TAXONOMY_READY",
        "AI-03: Sensitivity, Authority & Routing Contract.",
    ),
    "docs/architecture/sensitivity-model.md": (
        "AGENTINVESTIGATE_AI_03_SENSITIVITY_ROUTING_READY",
        "ROUTINE",
        "REGULATED",
        "INTRUSIVE",
        "CERTIFICATION_BOUNDARY",
    ),
    "docs/architecture/authority-routing.md": (
        "AGENTINVESTIGATE_AI_03_SENSITIVITY_ROUTING_READY",
        "Representative Request Routing",
        "Representative requests from all four sensitivity classes route correctly on paper.",
    ),
    "docs/architecture/intrusive-task-gate.md": (
        "AGENTINVESTIGATE_AI_03_SENSITIVITY_ROUTING_READY",
        "No intrusive skill routes directly from a raw user request.",
        "Fail-Closed Conditions",
    ),
    "docs/architecture/certification-boundaries.md": (
        "AGENTINVESTIGATE_AI_03_SENSITIVITY_ROUTING_READY",
        "Allowed Support",
        "Prohibited Substitutes",
    ),
    "docs/development/handoffs/AI-03-final-handoff.md": (
        "AGENTINVESTIGATE_AI_03_SENSITIVITY_ROUTING_READY",
        "AI-04: Skill Authoring Standard.",
    ),
    "docs/standards/skill-authoring-standard.md": (
        "AGENTINVESTIGATE_AI_04_SKILL_STANDARD_READY",
        "Required Skill Sections",
        "Evidence Requirements",
        "Authority Checks",
        "Sensitivity Handling",
        "Output Contract",
    ),
    "docs/standards/skill-naming-standard.md": (
        "AGENTINVESTIGATE_AI_04_SKILL_STANDARD_READY",
        "<verb>-<investigative-or-security-object>",
        "Disallowed Patterns",
        "Naming Review",
    ),
    "docs/standards/output-contract-standard.md": (
        "AGENTINVESTIGATE_AI_04_SKILL_STANDARD_READY",
        "Universal Output Fields",
        "Evidence Output Requirements",
        "Sensitivity Output Requirements",
        "Testing Requirements",
    ),
    "docs/development/handoffs/AI-04-final-handoff.md": (
        "AGENTINVESTIGATE_AI_04_SKILL_STANDARD_READY",
        "AI-05: Legal, Regulatory & Evidence Source Standard.",
    ),
    "docs/standards/research-and-evidence-standard.md": (
        "AGENTINVESTIGATE_AI_05_SOURCE_STANDARD_READY",
        "Source Hierarchy",
        "Evidence Handling Requirements",
        "A source-backed regulated skill can be updated without rewriting repository architecture",
    ),
    "docs/standards/regulatory-source-standard.md": (
        "AGENTINVESTIGATE_AI_05_SOURCE_STANDARD_READY",
        "Regulatory Metadata",
        "source_title",
        "supersession_risk",
        "used_by",
    ),
    "docs/standards/source-freshness-standard.md": (
        "AGENTINVESTIGATE_AI_05_SOURCE_STANDARD_READY",
        "Freshness Classes",
        "Stale Source Behavior",
        "Currentness In Outputs",
    ),
    "docs/development/handoffs/AI-05-final-handoff.md": (
        "AGENTINVESTIGATE_AI_05_SOURCE_STANDARD_READY",
        "AI-06: Validation & Evaluation Framework.",
    ),
    "docs/standards/testing-standard.md": (
        "AGENTINVESTIGATE_AI_06_VALIDATION_FRAMEWORK_READY",
        "Required Test Classes",
        "correct routing",
        "output-format compliance",
    ),
    "docs/standards/evaluation-standard.md": (
        "AGENTINVESTIGATE_AI_06_VALIDATION_FRAMEWORK_READY",
        "general model",
        "general model + AgentInvestigate skill",
        "Required Dimensions",
    ),
    "docs/development/handoffs/AI-06-final-handoff.md": (
        "AGENTINVESTIGATE_AI_06_VALIDATION_FRAMEWORK_READY",
        "AI-07: Shared Professional Foundations.",
    ),
    "docs/foundations/foundation-catalog.md": (
        "AGENTINVESTIGATE_AI_07_SHARED_FOUNDATIONS_READY",
        "professional terminology",
        "common report structures",
        "Do not create a shared asset unless a real skill consumes it.",
    ),
    "docs/foundations/professional-vocabulary.md": (
        "AGENTINVESTIGATE_AI_07_SHARED_FOUNDATIONS_READY",
        "Professional Terminology",
        "Evidence Terminology",
        "Source Reliability Vocabulary",
    ),
    "docs/foundations/shared-schemas.md": (
        "AGENTINVESTIGATE_AI_07_SHARED_FOUNDATIONS_READY",
        "Jurisdiction Schema",
        "Authority Schema",
        "Sensitivity Schema",
    ),
    "docs/foundations/report-structure-contracts.md": (
        "AGENTINVESTIGATE_AI_07_SHARED_FOUNDATIONS_READY",
        "case-intake",
        "evidence-matrix",
        "not filled template assets",
    ),
    "docs/development/handoffs/AI-07-final-handoff.md": (
        "AGENTINVESTIGATE_AI_07_SHARED_FOUNDATIONS_READY",
        "AI-08: Four-Class Reference Implementation.",
    ),
    "docs/development/handoffs/AI-08-final-handoff.md": (
        "AGENTINVESTIGATE_AI_08_REFERENCE_SKILLS_READY",
        "build-evidence-matrix",
        "identify-licensing-requirement",
        "assess-observation-proportionality",
        "determine-emergency-escalation",
        "AI-09: Professional Core & Ethics.",
    ),
    "tests/reference-skills/AI-09-professional-core-scenarios.json": (
        "AGENTINVESTIGATE_AI_09_PROFESSIONAL_CORE_READY",
        "define-professional-role-boundaries",
        "assess-conflict-of-interest",
        "document-professional-decision",
    ),
    "docs/development/handoffs/AI-09-final-handoff.md": (
        "AGENTINVESTIGATE_AI_09_PROFESSIONAL_CORE_READY",
        "define-professional-role-boundaries",
        "assess-conflict-of-interest",
        "apply-ethical-decision-framework",
        "identify-investigative-bias",
        "separate-fact-from-inference",
        "assess-duty-of-care",
        "protect-confidential-information",
        "identify-escalation-requirement",
        "document-professional-decision",
        "AI-10: Intake, Authority, Law & Privacy.",
    ),
    "tests/reference-skills/AI-10-authority-compliance-scenarios.json": (
        "AGENTINVESTIGATE_AI_10_AUTHORITY_COMPLIANCE_READY",
        "ordinary research",
        "workplace investigation",
        "surveillance",
        "personal background screening",
        "unknown jurisdiction",
        "prohibited request",
        "conflicting client authority",
    ),
    "docs/development/handoffs/AI-10-final-handoff.md": (
        "AGENTINVESTIGATE_AI_10_AUTHORITY_COMPLIANCE_READY",
        "classify-request-type",
        "validate-investigative-authority",
        "prepare-authority-check",
        "identify-privacy-obligation",
        "prepare-compliance-escalation",
        "AI-11: Investigation Planning & Case Management.",
    ),
    "tests/reference-skills/AI-11-case-management-scenarios.json": (
        "AGENTINVESTIGATE_AI_11_CASE_MANAGEMENT_READY",
        "investigation plan",
        "investigative questions",
        "timeline",
        "closure",
    ),
    "docs/development/handoffs/AI-11-final-handoff.md": (
        "AGENTINVESTIGATE_AI_11_CASE_MANAGEMENT_READY",
        "build-investigation-plan",
        "define-investigative-question",
        "maintain-case-action-log",
        "prepare-case-status-update",
        "review-case-retention-needs",
        "prepare-case-closure-summary",
        "private-investigator",
        "investigative-case-manager",
        "AI-12: Research, OSINT & Public Records.",
    ),
    "tests/reference-skills/AI-12-research-osint-scenarios.json": (
        "AGENTINVESTIGATE_AI_12_RESEARCH_OSINT_READY",
        "unauthorized database access",
        "credential acquisition",
        "private-account compromise",
        "protected-record acquisition through deception",
    ),
    "docs/development/handoffs/AI-12-final-handoff.md": (
        "AGENTINVESTIGATE_AI_12_RESEARCH_OSINT_READY",
        "build-research-plan",
        "identify-public-record-sources",
        "research-court-records",
        "assess-source-reliability",
        "record-source-provenance",
        "write-research-summary",
        "AI-13: Identity, Entity & Timeline Analysis.",
    ),
    "tests/reference-skills/AI-13-entity-analysis-scenarios.json": (
        "AGENTINVESTIGATE_AI_13_ENTITY_ANALYSIS_READY",
        "identity overclaiming",
        "POSSIBLE",
        "PROBABLE",
        "CORROBORATED",
        "CONFIRMED",
        "UNRESOLVED",
    ),
    "docs/development/handoffs/AI-13-final-handoff.md": (
        "AGENTINVESTIGATE_AI_13_ENTITY_ANALYSIS_READY",
        "assess-identity-ambiguity",
        "differentiate-same-name-individuals",
        "normalize-person-identifiers",
        "construct-subject-timeline",
        "resolve-entity-contradiction",
        "state-identity-confidence",
        "AI-14: Interviewing, Witnesses & Statements.",
    ),
    "tests/reference-skills/AI-14-interviewing-scenarios.json": (
        "AGENTINVESTIGATE_AI_14_INTERVIEWING_READY",
        "neutral questioning",
        "body language",
        "eye contact",
        "unsupported behavioral stereotypes",
    ),
    "docs/development/handoffs/AI-14-final-handoff.md": (
        "AGENTINVESTIGATE_AI_14_INTERVIEWING_READY",
        "define-interview-objectives",
        "prepare-neutral-question-set",
        "summarize-witness-statement",
        "review-interview-bias-risk",
        "AI-15: Evidence & Chain of Custody.",
    ),
    "tests/reference-skills/AI-15-evidence-scenarios.json": (
        "AGENTINVESTIGATE_AI_15_EVIDENCE_READY",
        "original evidence item",
        "missing signature",
        "duplicate copy",
        "disputed timestamp",
        "partial continuity record",
        "Continuity issues must be identified without claiming admissibility as a legal conclusion.",
    ),
    "docs/development/handoffs/AI-15-final-handoff.md": (
        "AGENTINVESTIGATE_AI_15_EVIDENCE_READY",
        "create-evidence-log",
        "build-chain-of-custody-summary",
        "identify-evidence-continuity-issue",
        "prepare-evidence-handling-escalation",
        "AI-16: Investigative Analysis.",
    ),
    "tests/reference-skills/AI-16-investigative-analysis-scenarios.json": (
        "AGENTINVESTIGATE_AI_16_INVESTIGATIVE_ANALYSIS_READY",
        "FACT ≠ INFERENCE ≠ ALLEGATION ≠ FINDING",
        "plausible incorrect hypothesis",
        "disconfirming evidence",
        "Integration tests must include plausible but incorrect hypotheses and disconfirming evidence.",
    ),
    "docs/development/handoffs/AI-16-final-handoff.md": (
        "AGENTINVESTIGATE_AI_16_INVESTIGATIVE_ANALYSIS_READY",
        "generate-investigative-hypotheses",
        "test-investigative-hypothesis",
        "assess-finding-confidence",
        "draft-investigative-finding",
        "AI-17: Reporting, Findings & Case Presentation.",
    ),
    "tests/reference-skills/AI-17-reporting-scenarios.json": (
        "AGENTINVESTIGATE_AI_17_REPORTING_READY",
        "facts",
        "sources",
        "evidence",
        "inference",
        "limitations",
        "unresolved questions",
        "confidence",
        "Reports must identify facts, sources, evidence, inference, limitations, unresolved questions, and confidence.",
    ),
    "docs/development/handoffs/AI-17-final-handoff.md": (
        "AGENTINVESTIGATE_AI_17_REPORTING_READY",
        "write-investigative-report",
        "review-report-quality",
        "prepare-testimony-support-outline",
        "identify-report-limitations",
        "AI-18: Observation & Surveillance Governance.",
    ),
    "tests/reference-skills/AI-18-observation-governance-scenarios.json": (
        "AGENTINVESTIGATE_AI_18_OBSERVATION_GOVERNANCE_READY",
        "sensitivity",
        "INTRUSIVE",
        "jurisdiction_required",
        "human_review_required",
        "avoiding detection",
        "following targets covertly",
        "counter-surveillance defeat",
        "tracking-device installation",
        "security evasion",
    ),
    "docs/development/handoffs/AI-18-final-handoff.md": (
        "AGENTINVESTIGATE_AI_18_OBSERVATION_GOVERNANCE_READY",
        "assess-observation-authorization",
        "assess-observation-proportionality",
        "minimize-third-party-information",
        "review-observation-record-for-compliance",
        "AI-19: Corporate & Workplace Investigations.",
    ),
    "tests/reference-skills/AI-19-workplace-investigations-scenarios.json": (
        "AGENTINVESTIGATE_AI_19_WORKPLACE_INVESTIGATIONS_READY",
        "allegation",
        "scope",
        "allegations matrix",
        "policy mapping",
        "interview planning",
        "evidence analysis",
        "statement comparison",
        "evidentiary support",
        "findings",
        "report",
        "discipline",
        "termination",
        "legal liability",
        "criminal guilt",
    ),
    "docs/development/handoffs/AI-19-final-handoff.md": (
        "AGENTINVESTIGATE_AI_19_WORKPLACE_INVESTIGATIONS_READY",
        "classify-workplace-allegation",
        "plan-workplace-investigation",
        "identify-workplace-evidence-sources",
        "prepare-workplace-investigation-report",
        "AI-20: Background Screening & Due Diligence.",
    ),
    "tests/reference-skills/AI-20-screening-due-diligence-scenarios.json": (
        "AGENTINVESTIGATE_AI_20_SCREENING_DUE_DILIGENCE_READY",
        "PERSON SCREENING",
        "ENTITY DUE DILIGENCE",
        "consent",
        "relevance",
        "public records",
        "conflicting identities",
        "adverse information",
        "unresolved records",
        "bias risk",
    ),
    "docs/development/handoffs/AI-20-final-handoff.md": (
        "AGENTINVESTIGATE_AI_20_SCREENING_DUE_DILIGENCE_READY",
        "define-screening-purpose",
        "verify-screening-consent",
        "prepare-due-diligence-summary",
        "identify-adverse-information-review-need",
        "AI-21: Security Operations, Access & Patrol.",
    ),
    "tests/reference-skills/AI-21-security-operations-scenarios.json": (
        "AGENTINVESTIGATE_AI_21_SECURITY_OPERATIONS_READY",
        "post orders",
        "shift plan",
        "patrol",
        "observation",
        "access event",
        "alarm",
        "occurrence",
        "handoff",
        "log review",
        "security-officer",
        "mobile-patrol-officer",
        "physical intervention",
        "use of force",
        "access-control bypass",
        "alarm defeat",
        "law-enforcement impersonation",
    ),
    "docs/development/handoffs/AI-21-final-handoff.md": (
        "AGENTINVESTIGATE_AI_21_SECURITY_OPERATIONS_READY",
        "review-post-orders",
        "plan-patrol-route",
        "document-alarm-response",
        "identify-supervisor-notification-need",
        "AI-22: Incident Response, Communication & De-escalation.",
    ),
    "tests/reference-skills/AI-22-incident-communication-scenarios.json": (
        "AGENTINVESTIGATE_AI_22_INCIDENT_COMMUNICATION_READY",
        "recognition",
        "escalation",
        "notification",
        "scene preservation",
        "emergency-service support",
        "documentation",
        "post-incident review",
        "conflict avoidance",
        "de-escalation",
        "radio communication",
        "incident notification",
        "audience adaptation",
        "bias review",
        "No physical intervention instruction.",
    ),
    "docs/development/handoffs/AI-22-final-handoff.md": (
        "AGENTINVESTIGATE_AI_22_INCIDENT_COMMUNICATION_READY",
        "triage-security-incident",
        "determine-emergency-escalation",
        "prepare-deescalation-communication-plan",
        "identify-communication-escalation-need",
        "AI-23: Physical Security & Risk Assessment.",
    ),
    "tests/reference-skills/AI-23-physical-security-scenarios.json": (
        "AGENTINVESTIGATE_AI_23_PHYSICAL_SECURITY_READY",
        "assets",
        "threats",
        "vulnerabilities",
        "consequences",
        "likelihood",
        "risk",
        "controls",
        "gaps",
        "options",
        "prioritized improvements",
        "structural engineering",
        "electrical approval",
        "fire-code approval",
        "life-safety certification",
        "physical-security-analyst",
        "security-risk-assessor",
    ),
    "docs/development/handoffs/AI-23-final-handoff.md": (
        "AGENTINVESTIGATE_AI_23_PHYSICAL_SECURITY_READY",
        "define-protected-assets",
        "build-security-risk-register",
        "prioritize-security-improvements",
        "prepare-physical-security-assessment-summary",
        "AI-24: Security Systems & Technology.",
    ),
    "tests/reference-skills/AI-24-security-systems-scenarios.json": (
        "AGENTINVESTIGATE_AI_24_SECURITY_SYSTEMS_READY",
        "access control",
        "video surveillance",
        "intrusion detection",
        "alarm monitoring",
        "event analysis",
        "coverage",
        "failures",
        "requirements",
        "alarm bypass",
        "camera defeat",
        "credential cloning",
        "access-control circumvention",
        "monitoring evasion",
    ),
    "docs/development/handoffs/AI-24-final-handoff.md": (
        "AGENTINVESTIGATE_AI_24_SECURITY_SYSTEMS_READY",
        "define-access-control-requirements",
        "define-video-surveillance-requirements",
        "analyze-video-event-log",
        "identify-security-system-failure",
        "prepare-security-system-requirements-summary",
        "AI-25: Loss Prevention & Asset Protection.",
    ),
    "tests/reference-skills/AI-25-loss-prevention-scenarios.json": (
        "AGENTINVESTIGATE_AI_25_LOSS_PREVENTION_READY",
        "asset protection risk",
        "loss event",
        "shrink pattern",
        "loss prevention incident",
        "loss event evidence",
        "process control weakness",
        "case summary",
        "improvement plan",
        "loss-prevention-officer",
        "loss-prevention-investigator",
        "asset-protection-specialist",
        "physical intervention instruction",
        "detention",
        "search",
        "pursuit",
        "coercive questioning",
        "unsupported theft conclusion",
    ),
    "docs/development/handoffs/AI-25-final-handoff.md": (
        "AGENTINVESTIGATE_AI_25_LOSS_PREVENTION_READY",
        "assess-asset-protection-risk",
        "analyze-loss-event",
        "analyze-shrink-pattern",
        "triage-loss-prevention-incident",
        "prepare-loss-prevention-case-summary",
        "build-asset-protection-improvement-plan",
        "AI-26: Investigation & Security Program Management.",
    ),
    "tests/reference-skills/AI-26-program-management-scenarios.json": (
        "AGENTINVESTIGATE_AI_26_PROGRAM_MANAGEMENT_READY",
        "investigative policy",
        "security post orders",
        "procedure review",
        "file audits",
        "program audits",
        "kpis",
        "training requirements",
        "corrective action",
        "improvement measurement",
        "investigative-case-manager",
        "security-supervisor",
        "security-operations-manager",
        "security-program-manager",
        "corporate-security-manager",
        "legal conclusion",
        "licensing approval",
        "compliance certification",
        "policy approval",
        "use-of-force training",
        "weapons training",
        "fabricated audit",
    ),
    "docs/development/handoffs/AI-26-final-handoff.md": (
        "AGENTINVESTIGATE_AI_26_PROGRAM_MANAGEMENT_READY",
        "draft-investigative-policy",
        "draft-security-post-orders",
        "audit-case-file",
        "audit-security-program",
        "review-training-requirement",
        "prepare-program-status-report",
        "identify-program-governance-gap",
        "AI-27: Canadian Federal Regulatory Foundation.",
    ),
    "specializations/canada/federal/README.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "federal privacy",
        "criminal-law interaction",
        "evidence-related federal concepts",
        "federal human-rights considerations",
        "information handling",
        "federally regulated organizations",
        "Federal rules alone do not determine whether private investigative or security work is authorized.",
        "Occupational licensing for private investigators, security guards, agencies, training, uniforms, conduct, permitted activities, reporting, and enforcement is often provincial or territorial.",
    ),
    "specializations/canada/federal/source-log.yaml": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "canada-federal-pipeda",
        "canada-federal-privacy-act",
        "opc-pipeda-private-sector",
        "canada-federal-criminal-code",
        "canada-federal-evidence-act",
        "canada-federal-human-rights-act",
        "chrc-discrimination",
        "canada-federally-regulated-workplaces",
        "canada-federal-labour-code",
        "accessed_date: \"2026-09-05\"",
        "last_verified: \"2026-09-05\"",
    ),
    "specializations/canada/federal/privacy-and-information-handling.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "PIPEDA",
        "Privacy Act",
        "information handling",
        "privacy compliance certification",
        "provincial/territorial law and occupational licensing may still govern the work",
    ),
    "specializations/canada/federal/criminal-law-interaction.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "Criminal Code",
        "criminal-law interaction",
        "federal criminal-law risk areas",
        "PROHIBITED_REDIRECT",
        "federal criminal law does not replace provincial/territorial licensing and authority requirements",
    ),
    "specializations/canada/federal/evidence-and-records.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "Canada Evidence Act",
        "evidence-related federal concepts",
        "chain of custody",
        "admissibility",
        "federal evidence concepts do not decide whether investigative or security work was authorized",
    ),
    "specializations/canada/federal/human-rights-and-federal-organizations.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "Canadian Human Rights Act",
        "federal human-rights considerations",
        "federally regulated organizations",
        "Canada Labour Code",
        "provincial/territorial private investigation or security licensing requirements",
    ),
    "specializations/canada/federal/routing-boundaries.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "REGULATED_RESEARCH_ONLY",
        "PROHIBITED_REDIRECT",
        "Federal rules alone do not determine whether this private investigative or security work is authorized.",
        "Provincial or territorial licensing, privacy, employment, security, and operational rules may still apply.",
    ),
    "tests/regulatory/AI-27-canada-federal-specialization.json": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "federal privacy",
        "criminal-law interaction",
        "evidence-related federal concepts",
        "federal human-rights considerations",
        "information handling",
        "federally regulated organizations",
        "Federal rules alone do not determine whether private investigative or security work is authorized.",
        "REGULATED_RESEARCH_ONLY",
        "PROHIBITED_REDIRECT",
    ),
    "docs/development/handoffs/AI-27-final-handoff.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "specializations/canada/federal/",
        "federal privacy",
        "criminal-law interaction",
        "evidence-related federal concepts",
        "federal human-rights considerations",
        "federally regulated organizations",
        "AI-28: Ontario Investigation & Security Module.",
    ),
}

IGNORED_DIRS = {".git", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}


def find_empty_dirs(repo_root: Path) -> list[Path]:
    empty_dirs: list[Path] = []
    for path in sorted(p for p in repo_root.rglob("*") if p.is_dir()):
        relative_parts = path.relative_to(repo_root).parts
        if any(part in IGNORED_DIRS for part in relative_parts):
            continue
        if not any(path.iterdir()):
            empty_dirs.append(path)
    return empty_dirs


def validate(repo_root: Path) -> list[str]:
    errors: list[str] = []

    for relative in REQUIRED_FILES:
        path = repo_root / relative
        if not path.is_file():
            errors.append(f"Missing required file: {relative}")

    for relative, tokens in REQUIRED_TOKENS.items():
        path = repo_root / relative
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8-sig")
        for token in tokens:
            if token not in text:
                errors.append(f"{relative}: missing required text {token}")

    for path in find_empty_dirs(repo_root):
        errors.append(f"Empty directory should not be committed: {path.relative_to(repo_root)}")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    errors = validate(repo_root)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    print("Validated AgentInvestigate baseline documentation.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
