from __future__ import annotations

import argparse
import sys
from pathlib import Path


REQUIRED_FILES = (
    "README.md",
    "ROADMAP.md",
    "CONTRIBUTING.md",
    "CHANGELOG.md",
    "LICENSE",
    "AGENTS.md",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
    ".gitattributes",
    ".gitignore",
    "docs/development/AI-00-baseline-audit.md",
    "docs/development/handoffs/AI-00-final-handoff.md",
    "docs/architecture/domain-contract.md",
    "docs/architecture/scope-boundaries.md",
    "docs/architecture/prohibited-capabilities.md",
    "docs/development/handoffs/AI-01-final-handoff.md",
    "docs/architecture/master-taxonomy-v1.md",
    "docs/architecture/taxonomy-index.yaml",
    "docs/development/handoffs/AI-02-final-handoff.md",
    "docs/architecture/sensitivity-model.md",
    "docs/architecture/authority-routing.md",
    "docs/architecture/intrusive-task-gate.md",
    "docs/architecture/certification-boundaries.md",
    "docs/development/handoffs/AI-03-final-handoff.md",
    "docs/standards/skill-authoring-standard.md",
    "docs/standards/skill-naming-standard.md",
    "docs/standards/output-contract-standard.md",
    "docs/development/handoffs/AI-04-final-handoff.md",
    "docs/standards/research-and-evidence-standard.md",
    "docs/standards/regulatory-source-standard.md",
    "docs/standards/source-freshness-standard.md",
    "docs/development/handoffs/AI-05-final-handoff.md",
    "docs/standards/testing-standard.md",
    "docs/standards/evaluation-standard.md",
    "tests/validation-scenarios.json",
    "tests/evaluation-rubric.json",
    "docs/development/handoffs/AI-06-final-handoff.md",
    "docs/foundations/foundation-catalog.md",
    "docs/foundations/professional-vocabulary.md",
    "docs/foundations/shared-schemas.md",
    "docs/foundations/report-structure-contracts.md",
    "docs/foundations/foundation-consumer-map.json",
    "docs/development/handoffs/AI-07-final-handoff.md",
    "tests/reference-skills/AI-08-reference-scenarios.json",
    "docs/development/handoffs/AI-08-final-handoff.md",
    "tests/reference-skills/AI-09-professional-core-scenarios.json",
    "docs/development/handoffs/AI-09-final-handoff.md",
    "tests/reference-skills/AI-10-authority-compliance-scenarios.json",
    "docs/development/handoffs/AI-10-final-handoff.md",
    "tests/reference-skills/AI-11-case-management-scenarios.json",
    "docs/development/handoffs/AI-11-final-handoff.md",
    "tests/reference-skills/AI-12-research-osint-scenarios.json",
    "docs/development/handoffs/AI-12-final-handoff.md",
    "tests/reference-skills/AI-13-entity-analysis-scenarios.json",
    "docs/development/handoffs/AI-13-final-handoff.md",
    "tests/reference-skills/AI-14-interviewing-scenarios.json",
    "docs/development/handoffs/AI-14-final-handoff.md",
    "tests/reference-skills/AI-15-evidence-scenarios.json",
    "docs/development/handoffs/AI-15-final-handoff.md",
    "tests/reference-skills/AI-16-investigative-analysis-scenarios.json",
    "docs/development/handoffs/AI-16-final-handoff.md",
    "tests/reference-skills/AI-17-reporting-scenarios.json",
    "docs/development/handoffs/AI-17-final-handoff.md",
    "tests/reference-skills/AI-18-observation-governance-scenarios.json",
    "docs/development/handoffs/AI-18-final-handoff.md",
    "tests/reference-skills/AI-19-workplace-investigations-scenarios.json",
    "docs/development/handoffs/AI-19-final-handoff.md",
    "tests/reference-skills/AI-20-screening-due-diligence-scenarios.json",
    "docs/development/handoffs/AI-20-final-handoff.md",
    "tests/reference-skills/AI-21-security-operations-scenarios.json",
    "docs/development/handoffs/AI-21-final-handoff.md",
    "tests/reference-skills/AI-22-incident-communication-scenarios.json",
    "docs/development/handoffs/AI-22-final-handoff.md",
    "tests/reference-skills/AI-23-physical-security-scenarios.json",
    "docs/development/handoffs/AI-23-final-handoff.md",
    "tests/reference-skills/AI-24-security-systems-scenarios.json",
    "docs/development/handoffs/AI-24-final-handoff.md",
    "tests/reference-skills/AI-25-loss-prevention-scenarios.json",
    "docs/development/handoffs/AI-25-final-handoff.md",
    "tests/reference-skills/AI-26-program-management-scenarios.json",
    "docs/development/handoffs/AI-26-final-handoff.md",
    "specializations/canada/federal/README.md",
    "specializations/canada/federal/source-log.yaml",
    "specializations/canada/federal/privacy-and-information-handling.md",
    "specializations/canada/federal/criminal-law-interaction.md",
    "specializations/canada/federal/evidence-and-records.md",
    "specializations/canada/federal/human-rights-and-federal-organizations.md",
    "specializations/canada/federal/routing-boundaries.md",
    "tests/regulatory/AI-27-canada-federal-specialization.json",
    "docs/development/handoffs/AI-27-final-handoff.md",
    "specializations/canada/ontario/README.md",
    "specializations/canada/ontario/source-log.yaml",
    "specializations/canada/ontario/licensing-and-registration.md",
    "specializations/canada/ontario/training-testing-and-conduct.md",
    "specializations/canada/ontario/authority-restrictions-and-security-operations.md",
    "specializations/canada/ontario/privacy-reporting-and-records.md",
    "specializations/canada/ontario/provincial-laws-map.md",
    "specializations/canada/ontario/routing-boundaries.md",
    "tests/regulatory/AI-28-ontario-specialization.json",
    "docs/development/handoffs/AI-28-final-handoff.md",
    "specializations/canada/british-columbia/README.md",
    "specializations/canada/british-columbia/source-log.yaml",
    "specializations/canada/british-columbia/licensing-and-registration.md",
    "specializations/canada/british-columbia/training-and-conduct.md",
    "specializations/canada/british-columbia/authority-restrictions-and-security-operations.md",
    "specializations/canada/british-columbia/privacy-reporting-and-records.md",
    "specializations/canada/british-columbia/provincial-laws-map.md",
    "specializations/canada/british-columbia/routing-boundaries.md",
    "tests/regulatory/AI-29-british-columbia-specialization.json",
    "docs/development/handoffs/AI-29-final-handoff.md",
    "specializations/canada/alberta/README.md",
    "specializations/canada/alberta/source-log.yaml",
    "specializations/canada/alberta/licensing-and-registration.md",
    "specializations/canada/alberta/training-examination-and-conduct.md",
    "specializations/canada/alberta/authority-restrictions-and-security-operations.md",
    "specializations/canada/alberta/privacy-reporting-and-records.md",
    "specializations/canada/alberta/provincial-laws-map.md",
    "specializations/canada/alberta/routing-boundaries.md",
    "tests/regulatory/AI-30-alberta-specialization.json",
    "docs/development/handoffs/AI-30-final-handoff.md",
    "docs/architecture/canadian-jurisdiction-roadmap.md",
    "tests/regulatory/AI-31-canadian-jurisdiction-framework.json",
    "docs/development/handoffs/AI-31-final-handoff.md",
    "docs/architecture/professional-skillset-composition.md",
    "skillsets/README.md",
    "skillsets/professional-skillsets.json",
    "tests/skillsets/AI-32-professional-skillset-composition.json",
    "docs/development/handoffs/AI-32-final-handoff.md",
    "docs/evaluation/multi-skill-integration-evaluation.md",
    "tests/integration/AI-33-multi-skill-integration-scenarios.json",
    "docs/development/handoffs/AI-33-final-handoff.md",
    "docs/evaluation/adversarial-safety-misuse-evaluation.md",
    "tests/safety/AI-34-adversarial-safety-misuse-scenarios.json",
    "docs/development/handoffs/AI-34-final-handoff.md",
    "docs/architecture/specialization-roadmap.md",
    "docs/development/handoffs/AI-35-final-handoff.md",
    "docs/development/handoffs/AI-36-final-handoff.md",
    "docs/evaluation/v1-release-candidate-audit.md",
    "tests/release/AI-37-v1-release-candidate-audit.json",
    "docs/development/handoffs/AI-37-final-handoff.md",
    "docs/release/public-release-distribution.md",
    "tests/release/AI-38-public-release-distribution.json",
    "docs/development/handoffs/AI-38-final-handoff.md",
    "docs/wiki/Home.md",
    "docs/wiki/_Sidebar.md",
    "docs/wiki/Getting-Started.md",
    "docs/wiki/Architecture-Overview.md",
    "docs/wiki/Skill-Catalog.md",
    "docs/wiki/Professional-Skillsets.md",
    "docs/wiki/Sensitivity-And-Routing.md",
    "docs/wiki/Jurisdiction-Model.md",
    "docs/wiki/Safety-Boundaries.md",
    "docs/wiki/Validation-And-Testing.md",
    "docs/wiki/Contributing-Guide.md",
    "docs/wiki/Release-Readiness.md",
    "scripts/validate-all.ps1",
    "scripts/validate-docs.py",
    "scripts/validate-taxonomy.py",
    "scripts/generate-taxonomy.py",
    "scripts/validate-routing.py",
    "scripts/validate-standards.py",
    "scripts/validate-tests.py",
    "scripts/validate-foundations.py",
    "scripts/validate-skills.py",
    "scripts/validate-specializations.py",
    "scripts/validate-skillsets.py",
    "scripts/validate-integration.py",
    "scripts/validate-safety.py",
    "scripts/validate-specialization-roadmap.py",
    "scripts/validate-public-readiness.py",
    "scripts/validate-v1-rc-audit.py",
    "scripts/validate-public-release-distribution.py",
    "scripts/generate-ai32-skillsets.py",
)

REQUIRED_TOKENS = {
    "ROADMAP.md": (
        "AgentInvestigate Development Roadmap",
        "Roadmap version: 0.1",
        "AGENTINVESTIGATE_DEVELOPMENT_ROADMAP_V0_1_READY",
    ),
    "docs/development/AI-00-baseline-audit.md": (
        "AGENTINVESTIGATE_AI_00_BASELINE_READY",
        "Source handling rule applied",
        "No skill folders, skillsets, specializations, shared assets, fixtures, or future-wave architecture files were created.",
    ),
    "docs/development/handoffs/AI-00-final-handoff.md": (
        "AGENTINVESTIGATE_AI_00_BASELINE_READY",
        "AI-01: Domain & Scope Contract.",
    ),
    "docs/architecture/domain-contract.md": (
        "AGENTINVESTIGATE_AI_01_DOMAIN_CONTRACT_READY",
        "Private Investigation",
        "Private Security",
        "Taxonomy Family Mapping",
        "Every roadmap taxonomy family maps cleanly to the domain contract.",
    ),
    "docs/architecture/scope-boundaries.md": (
        "AGENTINVESTIGATE_AI_01_DOMAIN_CONTRACT_READY",
        "In Scope",
        "Out Of Scope",
        "Required Gates",
        "Acceptance Criteria",
    ),
    "docs/architecture/prohibited-capabilities.md": (
        "AGENTINVESTIGATE_AI_01_DOMAIN_CONTRACT_READY",
        "Absolute Exclusions",
        "Response And Routing Rules",
        "Design Constraints For Future Skills",
    ),
    "docs/development/handoffs/AI-01-final-handoff.md": (
        "AGENTINVESTIGATE_AI_01_DOMAIN_CONTRACT_READY",
        "AI-02: Master Taxonomy Integration.",
    ),
    "docs/architecture/master-taxonomy-v1.md": (
        "AGENTINVESTIGATE_AI_02_MASTER_TAXONOMY_READY",
        "`docs/architecture/taxonomy-index.yaml` is the canonical taxonomy source.",
        "Exactly one canonical taxonomy source exists: docs/architecture/taxonomy-index.yaml",
    ),
    "docs/architecture/taxonomy-index.yaml": (
        "AGENTINVESTIGATE_AI_02_MASTER_TAXONOMY_READY",
        "AgentInvestigate Master Taxonomy v1.0",
        "\"skills\": 212",
    ),
    "docs/development/handoffs/AI-02-final-handoff.md": (
        "AGENTINVESTIGATE_AI_02_MASTER_TAXONOMY_READY",
        "AI-03: Sensitivity, Authority & Routing Contract.",
    ),
    "docs/architecture/sensitivity-model.md": (
        "AGENTINVESTIGATE_AI_03_SENSITIVITY_ROUTING_READY",
        "ROUTINE",
        "REGULATED",
        "INTRUSIVE",
        "CERTIFICATION_BOUNDARY",
    ),
    "docs/architecture/authority-routing.md": (
        "AGENTINVESTIGATE_AI_03_SENSITIVITY_ROUTING_READY",
        "Representative Request Routing",
        "Representative requests from all four sensitivity classes route correctly on paper.",
    ),
    "docs/architecture/intrusive-task-gate.md": (
        "AGENTINVESTIGATE_AI_03_SENSITIVITY_ROUTING_READY",
        "No intrusive skill routes directly from a raw user request.",
        "Fail-Closed Conditions",
    ),
    "docs/architecture/certification-boundaries.md": (
        "AGENTINVESTIGATE_AI_03_SENSITIVITY_ROUTING_READY",
        "Allowed Support",
        "Prohibited Substitutes",
    ),
    "docs/development/handoffs/AI-03-final-handoff.md": (
        "AGENTINVESTIGATE_AI_03_SENSITIVITY_ROUTING_READY",
        "AI-04: Skill Authoring Standard.",
    ),
    "docs/standards/skill-authoring-standard.md": (
        "AGENTINVESTIGATE_AI_04_SKILL_STANDARD_READY",
        "Required Skill Sections",
        "Evidence Requirements",
        "Authority Checks",
        "Sensitivity Handling",
        "Output Contract",
    ),
    "docs/standards/skill-naming-standard.md": (
        "AGENTINVESTIGATE_AI_04_SKILL_STANDARD_READY",
        "<verb>-<investigative-or-security-object>",
        "Disallowed Patterns",
        "Naming Review",
    ),
    "docs/standards/output-contract-standard.md": (
        "AGENTINVESTIGATE_AI_04_SKILL_STANDARD_READY",
        "Universal Output Fields",
        "Evidence Output Requirements",
        "Sensitivity Output Requirements",
        "Testing Requirements",
    ),
    "docs/development/handoffs/AI-04-final-handoff.md": (
        "AGENTINVESTIGATE_AI_04_SKILL_STANDARD_READY",
        "AI-05: Legal, Regulatory & Evidence Source Standard.",
    ),
    "docs/standards/research-and-evidence-standard.md": (
        "AGENTINVESTIGATE_AI_05_SOURCE_STANDARD_READY",
        "Source Hierarchy",
        "Evidence Handling Requirements",
        "A source-backed regulated skill can be updated without rewriting repository architecture",
    ),
    "docs/standards/regulatory-source-standard.md": (
        "AGENTINVESTIGATE_AI_05_SOURCE_STANDARD_READY",
        "Regulatory Metadata",
        "source_title",
        "supersession_risk",
        "used_by",
    ),
    "docs/standards/source-freshness-standard.md": (
        "AGENTINVESTIGATE_AI_05_SOURCE_STANDARD_READY",
        "Freshness Classes",
        "Stale Source Behavior",
        "Currentness In Outputs",
    ),
    "docs/development/handoffs/AI-05-final-handoff.md": (
        "AGENTINVESTIGATE_AI_05_SOURCE_STANDARD_READY",
        "AI-06: Validation & Evaluation Framework.",
    ),
    "docs/standards/testing-standard.md": (
        "AGENTINVESTIGATE_AI_06_VALIDATION_FRAMEWORK_READY",
        "Required Test Classes",
        "correct routing",
        "output-format compliance",
    ),
    "docs/standards/evaluation-standard.md": (
        "AGENTINVESTIGATE_AI_06_VALIDATION_FRAMEWORK_READY",
        "general model",
        "general model + AgentInvestigate skill",
        "Required Dimensions",
    ),
    "docs/development/handoffs/AI-06-final-handoff.md": (
        "AGENTINVESTIGATE_AI_06_VALIDATION_FRAMEWORK_READY",
        "AI-07: Shared Professional Foundations.",
    ),
    "docs/foundations/foundation-catalog.md": (
        "AGENTINVESTIGATE_AI_07_SHARED_FOUNDATIONS_READY",
        "professional terminology",
        "common report structures",
        "Do not create a shared asset unless a real skill consumes it.",
    ),
    "docs/foundations/professional-vocabulary.md": (
        "AGENTINVESTIGATE_AI_07_SHARED_FOUNDATIONS_READY",
        "Professional Terminology",
        "Evidence Terminology",
        "Source Reliability Vocabulary",
    ),
    "docs/foundations/shared-schemas.md": (
        "AGENTINVESTIGATE_AI_07_SHARED_FOUNDATIONS_READY",
        "Jurisdiction Schema",
        "Authority Schema",
        "Sensitivity Schema",
    ),
    "docs/foundations/report-structure-contracts.md": (
        "AGENTINVESTIGATE_AI_07_SHARED_FOUNDATIONS_READY",
        "case-intake",
        "evidence-matrix",
        "not filled template assets",
    ),
    "docs/development/handoffs/AI-07-final-handoff.md": (
        "AGENTINVESTIGATE_AI_07_SHARED_FOUNDATIONS_READY",
        "AI-08: Four-Class Reference Implementation.",
    ),
    "docs/development/handoffs/AI-08-final-handoff.md": (
        "AGENTINVESTIGATE_AI_08_REFERENCE_SKILLS_READY",
        "build-evidence-matrix",
        "identify-licensing-requirement",
        "assess-observation-proportionality",
        "determine-emergency-escalation",
        "AI-09: Professional Core & Ethics.",
    ),
    "tests/reference-skills/AI-09-professional-core-scenarios.json": (
        "AGENTINVESTIGATE_AI_09_PROFESSIONAL_CORE_READY",
        "define-professional-role-boundaries",
        "assess-conflict-of-interest",
        "document-professional-decision",
    ),
    "docs/development/handoffs/AI-09-final-handoff.md": (
        "AGENTINVESTIGATE_AI_09_PROFESSIONAL_CORE_READY",
        "define-professional-role-boundaries",
        "assess-conflict-of-interest",
        "apply-ethical-decision-framework",
        "identify-investigative-bias",
        "separate-fact-from-inference",
        "assess-duty-of-care",
        "protect-confidential-information",
        "identify-escalation-requirement",
        "document-professional-decision",
        "AI-10: Intake, Authority, Law & Privacy.",
    ),
    "tests/reference-skills/AI-10-authority-compliance-scenarios.json": (
        "AGENTINVESTIGATE_AI_10_AUTHORITY_COMPLIANCE_READY",
        "ordinary research",
        "workplace investigation",
        "surveillance",
        "personal background screening",
        "unknown jurisdiction",
        "prohibited request",
        "conflicting client authority",
    ),
    "docs/development/handoffs/AI-10-final-handoff.md": (
        "AGENTINVESTIGATE_AI_10_AUTHORITY_COMPLIANCE_READY",
        "classify-request-type",
        "validate-investigative-authority",
        "prepare-authority-check",
        "identify-privacy-obligation",
        "prepare-compliance-escalation",
        "AI-11: Investigation Planning & Case Management.",
    ),
    "tests/reference-skills/AI-11-case-management-scenarios.json": (
        "AGENTINVESTIGATE_AI_11_CASE_MANAGEMENT_READY",
        "investigation plan",
        "investigative questions",
        "timeline",
        "closure",
    ),
    "docs/development/handoffs/AI-11-final-handoff.md": (
        "AGENTINVESTIGATE_AI_11_CASE_MANAGEMENT_READY",
        "build-investigation-plan",
        "define-investigative-question",
        "maintain-case-action-log",
        "prepare-case-status-update",
        "review-case-retention-needs",
        "prepare-case-closure-summary",
        "private-investigator",
        "investigative-case-manager",
        "AI-12: Research, OSINT & Public Records.",
    ),
    "tests/reference-skills/AI-12-research-osint-scenarios.json": (
        "AGENTINVESTIGATE_AI_12_RESEARCH_OSINT_READY",
        "unauthorized database access",
        "credential acquisition",
        "private-account compromise",
        "protected-record acquisition through deception",
    ),
    "docs/development/handoffs/AI-12-final-handoff.md": (
        "AGENTINVESTIGATE_AI_12_RESEARCH_OSINT_READY",
        "build-research-plan",
        "identify-public-record-sources",
        "research-court-records",
        "assess-source-reliability",
        "record-source-provenance",
        "write-research-summary",
        "AI-13: Identity, Entity & Timeline Analysis.",
    ),
    "tests/reference-skills/AI-13-entity-analysis-scenarios.json": (
        "AGENTINVESTIGATE_AI_13_ENTITY_ANALYSIS_READY",
        "identity overclaiming",
        "POSSIBLE",
        "PROBABLE",
        "CORROBORATED",
        "CONFIRMED",
        "UNRESOLVED",
    ),
    "docs/development/handoffs/AI-13-final-handoff.md": (
        "AGENTINVESTIGATE_AI_13_ENTITY_ANALYSIS_READY",
        "assess-identity-ambiguity",
        "differentiate-same-name-individuals",
        "normalize-person-identifiers",
        "construct-subject-timeline",
        "resolve-entity-contradiction",
        "state-identity-confidence",
        "AI-14: Interviewing, Witnesses & Statements.",
    ),
    "tests/reference-skills/AI-14-interviewing-scenarios.json": (
        "AGENTINVESTIGATE_AI_14_INTERVIEWING_READY",
        "neutral questioning",
        "body language",
        "eye contact",
        "unsupported behavioral stereotypes",
    ),
    "docs/development/handoffs/AI-14-final-handoff.md": (
        "AGENTINVESTIGATE_AI_14_INTERVIEWING_READY",
        "define-interview-objectives",
        "prepare-neutral-question-set",
        "summarize-witness-statement",
        "review-interview-bias-risk",
        "AI-15: Evidence & Chain of Custody.",
    ),
    "tests/reference-skills/AI-15-evidence-scenarios.json": (
        "AGENTINVESTIGATE_AI_15_EVIDENCE_READY",
        "original evidence item",
        "missing signature",
        "duplicate copy",
        "disputed timestamp",
        "partial continuity record",
        "Continuity issues must be identified without claiming admissibility as a legal conclusion.",
    ),
    "docs/development/handoffs/AI-15-final-handoff.md": (
        "AGENTINVESTIGATE_AI_15_EVIDENCE_READY",
        "create-evidence-log",
        "build-chain-of-custody-summary",
        "identify-evidence-continuity-issue",
        "prepare-evidence-handling-escalation",
        "AI-16: Investigative Analysis.",
    ),
    "tests/reference-skills/AI-16-investigative-analysis-scenarios.json": (
        "AGENTINVESTIGATE_AI_16_INVESTIGATIVE_ANALYSIS_READY",
        "FACT ≠ INFERENCE ≠ ALLEGATION ≠ FINDING",
        "plausible incorrect hypothesis",
        "disconfirming evidence",
        "Integration tests must include plausible but incorrect hypotheses and disconfirming evidence.",
    ),
    "docs/development/handoffs/AI-16-final-handoff.md": (
        "AGENTINVESTIGATE_AI_16_INVESTIGATIVE_ANALYSIS_READY",
        "generate-investigative-hypotheses",
        "test-investigative-hypothesis",
        "assess-finding-confidence",
        "draft-investigative-finding",
        "AI-17: Reporting, Findings & Case Presentation.",
    ),
    "tests/reference-skills/AI-17-reporting-scenarios.json": (
        "AGENTINVESTIGATE_AI_17_REPORTING_READY",
        "facts",
        "sources",
        "evidence",
        "inference",
        "limitations",
        "unresolved questions",
        "confidence",
        "Reports must identify facts, sources, evidence, inference, limitations, unresolved questions, and confidence.",
    ),
    "docs/development/handoffs/AI-17-final-handoff.md": (
        "AGENTINVESTIGATE_AI_17_REPORTING_READY",
        "write-investigative-report",
        "review-report-quality",
        "prepare-testimony-support-outline",
        "identify-report-limitations",
        "AI-18: Observation & Surveillance Governance.",
    ),
    "tests/reference-skills/AI-18-observation-governance-scenarios.json": (
        "AGENTINVESTIGATE_AI_18_OBSERVATION_GOVERNANCE_READY",
        "sensitivity",
        "INTRUSIVE",
        "jurisdiction_required",
        "human_review_required",
        "avoiding detection",
        "following targets covertly",
        "counter-surveillance defeat",
        "tracking-device installation",
        "security evasion",
    ),
    "docs/development/handoffs/AI-18-final-handoff.md": (
        "AGENTINVESTIGATE_AI_18_OBSERVATION_GOVERNANCE_READY",
        "assess-observation-authorization",
        "assess-observation-proportionality",
        "minimize-third-party-information",
        "review-observation-record-for-compliance",
        "AI-19: Corporate & Workplace Investigations.",
    ),
    "tests/reference-skills/AI-19-workplace-investigations-scenarios.json": (
        "AGENTINVESTIGATE_AI_19_WORKPLACE_INVESTIGATIONS_READY",
        "allegation",
        "scope",
        "allegations matrix",
        "policy mapping",
        "interview planning",
        "evidence analysis",
        "statement comparison",
        "evidentiary support",
        "findings",
        "report",
        "discipline",
        "termination",
        "legal liability",
        "criminal guilt",
    ),
    "docs/development/handoffs/AI-19-final-handoff.md": (
        "AGENTINVESTIGATE_AI_19_WORKPLACE_INVESTIGATIONS_READY",
        "classify-workplace-allegation",
        "plan-workplace-investigation",
        "identify-workplace-evidence-sources",
        "prepare-workplace-investigation-report",
        "AI-20: Background Screening & Due Diligence.",
    ),
    "tests/reference-skills/AI-20-screening-due-diligence-scenarios.json": (
        "AGENTINVESTIGATE_AI_20_SCREENING_DUE_DILIGENCE_READY",
        "PERSON SCREENING",
        "ENTITY DUE DILIGENCE",
        "consent",
        "relevance",
        "public records",
        "conflicting identities",
        "adverse information",
        "unresolved records",
        "bias risk",
    ),
    "docs/development/handoffs/AI-20-final-handoff.md": (
        "AGENTINVESTIGATE_AI_20_SCREENING_DUE_DILIGENCE_READY",
        "define-screening-purpose",
        "verify-screening-consent",
        "prepare-due-diligence-summary",
        "identify-adverse-information-review-need",
        "AI-21: Security Operations, Access & Patrol.",
    ),
    "tests/reference-skills/AI-21-security-operations-scenarios.json": (
        "AGENTINVESTIGATE_AI_21_SECURITY_OPERATIONS_READY",
        "post orders",
        "shift plan",
        "patrol",
        "observation",
        "access event",
        "alarm",
        "occurrence",
        "handoff",
        "log review",
        "security-officer",
        "mobile-patrol-officer",
        "physical intervention",
        "use of force",
        "access-control bypass",
        "alarm defeat",
        "law-enforcement impersonation",
    ),
    "docs/development/handoffs/AI-21-final-handoff.md": (
        "AGENTINVESTIGATE_AI_21_SECURITY_OPERATIONS_READY",
        "review-post-orders",
        "plan-patrol-route",
        "document-alarm-response",
        "identify-supervisor-notification-need",
        "AI-22: Incident Response, Communication & De-escalation.",
    ),
    "tests/reference-skills/AI-22-incident-communication-scenarios.json": (
        "AGENTINVESTIGATE_AI_22_INCIDENT_COMMUNICATION_READY",
        "recognition",
        "escalation",
        "notification",
        "scene preservation",
        "emergency-service support",
        "documentation",
        "post-incident review",
        "conflict avoidance",
        "de-escalation",
        "radio communication",
        "incident notification",
        "audience adaptation",
        "bias review",
        "No physical intervention instruction.",
    ),
    "docs/development/handoffs/AI-22-final-handoff.md": (
        "AGENTINVESTIGATE_AI_22_INCIDENT_COMMUNICATION_READY",
        "triage-security-incident",
        "determine-emergency-escalation",
        "prepare-deescalation-communication-plan",
        "identify-communication-escalation-need",
        "AI-23: Physical Security & Risk Assessment.",
    ),
    "tests/reference-skills/AI-23-physical-security-scenarios.json": (
        "AGENTINVESTIGATE_AI_23_PHYSICAL_SECURITY_READY",
        "assets",
        "threats",
        "vulnerabilities",
        "consequences",
        "likelihood",
        "risk",
        "controls",
        "gaps",
        "options",
        "prioritized improvements",
        "structural engineering",
        "electrical approval",
        "fire-code approval",
        "life-safety certification",
        "physical-security-analyst",
        "security-risk-assessor",
    ),
    "docs/development/handoffs/AI-23-final-handoff.md": (
        "AGENTINVESTIGATE_AI_23_PHYSICAL_SECURITY_READY",
        "define-protected-assets",
        "build-security-risk-register",
        "prioritize-security-improvements",
        "prepare-physical-security-assessment-summary",
        "AI-24: Security Systems & Technology.",
    ),
    "tests/reference-skills/AI-24-security-systems-scenarios.json": (
        "AGENTINVESTIGATE_AI_24_SECURITY_SYSTEMS_READY",
        "access control",
        "video surveillance",
        "intrusion detection",
        "alarm monitoring",
        "event analysis",
        "coverage",
        "failures",
        "requirements",
        "alarm bypass",
        "camera defeat",
        "credential cloning",
        "access-control circumvention",
        "monitoring evasion",
    ),
    "docs/development/handoffs/AI-24-final-handoff.md": (
        "AGENTINVESTIGATE_AI_24_SECURITY_SYSTEMS_READY",
        "define-access-control-requirements",
        "define-video-surveillance-requirements",
        "analyze-video-event-log",
        "identify-security-system-failure",
        "prepare-security-system-requirements-summary",
        "AI-25: Loss Prevention & Asset Protection.",
    ),
    "tests/reference-skills/AI-25-loss-prevention-scenarios.json": (
        "AGENTINVESTIGATE_AI_25_LOSS_PREVENTION_READY",
        "asset protection risk",
        "loss event",
        "shrink pattern",
        "loss prevention incident",
        "loss event evidence",
        "process control weakness",
        "case summary",
        "improvement plan",
        "loss-prevention-officer",
        "loss-prevention-investigator",
        "asset-protection-specialist",
        "physical intervention instruction",
        "detention",
        "search",
        "pursuit",
        "coercive questioning",
        "unsupported theft conclusion",
    ),
    "docs/development/handoffs/AI-25-final-handoff.md": (
        "AGENTINVESTIGATE_AI_25_LOSS_PREVENTION_READY",
        "assess-asset-protection-risk",
        "analyze-loss-event",
        "analyze-shrink-pattern",
        "triage-loss-prevention-incident",
        "prepare-loss-prevention-case-summary",
        "build-asset-protection-improvement-plan",
        "AI-26: Investigation & Security Program Management.",
    ),
    "tests/reference-skills/AI-26-program-management-scenarios.json": (
        "AGENTINVESTIGATE_AI_26_PROGRAM_MANAGEMENT_READY",
        "investigative policy",
        "security post orders",
        "procedure review",
        "file audits",
        "program audits",
        "kpis",
        "training requirements",
        "corrective action",
        "improvement measurement",
        "investigative-case-manager",
        "security-supervisor",
        "security-operations-manager",
        "security-program-manager",
        "corporate-security-manager",
        "legal conclusion",
        "licensing approval",
        "compliance certification",
        "policy approval",
        "use-of-force training",
        "weapons training",
        "fabricated audit",
    ),
    "docs/development/handoffs/AI-26-final-handoff.md": (
        "AGENTINVESTIGATE_AI_26_PROGRAM_MANAGEMENT_READY",
        "draft-investigative-policy",
        "draft-security-post-orders",
        "audit-case-file",
        "audit-security-program",
        "review-training-requirement",
        "prepare-program-status-report",
        "identify-program-governance-gap",
        "AI-27: Canadian Federal Regulatory Foundation.",
    ),
    "specializations/canada/federal/README.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "federal privacy",
        "criminal-law interaction",
        "evidence-related federal concepts",
        "federal human-rights considerations",
        "information handling",
        "federally regulated organizations",
        "Federal rules alone do not determine whether private investigative or security work is authorized.",
        "Occupational licensing for private investigators, security guards, agencies, training, uniforms, conduct, permitted activities, reporting, and enforcement is often provincial or territorial.",
    ),
    "specializations/canada/federal/source-log.yaml": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "canada-federal-pipeda",
        "canada-federal-privacy-act",
        "opc-pipeda-private-sector",
        "canada-federal-criminal-code",
        "canada-federal-evidence-act",
        "canada-federal-human-rights-act",
        "chrc-discrimination",
        "canada-federally-regulated-workplaces",
        "canada-federal-labour-code",
        "accessed_date: \"2026-09-05\"",
        "last_verified: \"2026-09-05\"",
    ),
    "specializations/canada/federal/privacy-and-information-handling.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "PIPEDA",
        "Privacy Act",
        "information handling",
        "privacy compliance certification",
        "provincial/territorial law and occupational licensing may still govern the work",
    ),
    "specializations/canada/federal/criminal-law-interaction.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "Criminal Code",
        "criminal-law interaction",
        "federal criminal-law risk areas",
        "PROHIBITED_REDIRECT",
        "federal criminal law does not replace provincial/territorial licensing and authority requirements",
    ),
    "specializations/canada/federal/evidence-and-records.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "Canada Evidence Act",
        "evidence-related federal concepts",
        "chain of custody",
        "admissibility",
        "federal evidence concepts do not decide whether investigative or security work was authorized",
    ),
    "specializations/canada/federal/human-rights-and-federal-organizations.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "Canadian Human Rights Act",
        "federal human-rights considerations",
        "federally regulated organizations",
        "Canada Labour Code",
        "provincial/territorial private investigation or security licensing requirements",
    ),
    "specializations/canada/federal/routing-boundaries.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "REGULATED_RESEARCH_ONLY",
        "PROHIBITED_REDIRECT",
        "Federal rules alone do not determine whether this private investigative or security work is authorized.",
        "Provincial or territorial licensing, privacy, employment, security, and operational rules may still apply.",
    ),
    "tests/regulatory/AI-27-canada-federal-specialization.json": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "federal privacy",
        "criminal-law interaction",
        "evidence-related federal concepts",
        "federal human-rights considerations",
        "information handling",
        "federally regulated organizations",
        "Federal rules alone do not determine whether private investigative or security work is authorized.",
        "REGULATED_RESEARCH_ONLY",
        "PROHIBITED_REDIRECT",
    ),
    "docs/development/handoffs/AI-27-final-handoff.md": (
        "AGENTINVESTIGATE_AI_27_CANADA_FEDERAL_READY",
        "specializations/canada/federal/",
        "federal privacy",
        "criminal-law interaction",
        "evidence-related federal concepts",
        "federal human-rights considerations",
        "federally regulated organizations",
        "AI-28: Ontario Investigation & Security Module.",
    ),
    "specializations/canada/ontario/README.md": (
        "AGENTINVESTIGATE_AI_28_ONTARIO_READY",
        "investigator licensing",
        "security licensing",
        "training",
        "professional conduct",
        "permitted authorities",
        "restrictions",
        "privacy interaction",
        "reporting",
        "security operations",
        "provincial laws materially relevant to scoped skills",
        "Ontario sources can identify provincial issue areas, but they do not by themselves authorize private investigative or security work without current licensing, authority, role, purpose, and qualified review.",
    ),
    "specializations/canada/ontario/source-log.yaml": (
        "AGENTINVESTIGATE_AI_28_ONTARIO_READY",
        "ontario-psisa-act",
        "ontario-individual-licence-guidance",
        "ontario-agency-corporation-licence-guidance",
        "ontario-basic-training-guidance",
        "ontario-testing-guidance",
        "ontario-code-of-conduct-regulation",
        "ontario-recordkeeping-regulation",
        "ontario-information-to-registrar-regulation",
        "ontario-fippa",
        "ontario-mfippa",
        "ontario-phipa",
        "ontario-ipc-video-surveillance",
        "ontario-human-rights-code",
        "ontario-ohsa",
        "ontario-trespass-to-property-act",
        "ontario-aoda",
        "accessed_date: \"2026-09-05\"",
        "last_verified: \"2026-09-05\"",
    ),
    "specializations/canada/ontario/licensing-and-registration.md": (
        "AGENTINVESTIGATE_AI_28_ONTARIO_READY",
        "investigator licensing",
        "security licensing",
        "dual licences",
        "agency or corporation licence",
        "clean criminal record",
        "REGULATED_RESEARCH_ONLY",
        "PROHIBITED_REDIRECT",
    ),
    "specializations/canada/ontario/training-testing-and-conduct.md": (
        "AGENTINVESTIGATE_AI_28_ONTARIO_READY",
        "training",
        "professional conduct",
        "basic training",
        "ministry test",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
    ),
    "specializations/canada/ontario/authority-restrictions-and-security-operations.md": (
        "AGENTINVESTIGATE_AI_28_ONTARIO_READY",
        "permitted authorities",
        "restrictions",
        "security operations",
        "uniform",
        "equipment",
        "post orders",
        "trespass",
        "PROHIBITED_REDIRECT",
    ),
    "specializations/canada/ontario/privacy-reporting-and-records.md": (
        "AGENTINVESTIGATE_AI_28_ONTARIO_READY",
        "privacy interaction",
        "reporting",
        "recordkeeping",
        "FIPPA",
        "MFIPPA",
        "PHIPA",
        "IPC video surveillance guidance",
        "INTRUSIVE_GATE_REQUIRED",
    ),
    "specializations/canada/ontario/provincial-laws-map.md": (
        "AGENTINVESTIGATE_AI_28_ONTARIO_READY",
        "provincial laws materially relevant to scoped skills",
        "Private Security and Investigative Services Act",
        "Human Rights Code",
        "Occupational Health and Safety Act",
        "Trespass to Property Act",
        "Employment Standards Act",
        "Accessibility for Ontarians with Disabilities Act",
    ),
    "specializations/canada/ontario/routing-boundaries.md": (
        "AGENTINVESTIGATE_AI_28_ONTARIO_READY",
        "REGULATED_RESEARCH_ONLY",
        "INTRUSIVE_GATE_REQUIRED",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
        "Ontario sources can identify provincial issue areas, but they do not by themselves authorize private investigative or security work without current licensing, authority, role, purpose, and qualified review.",
        "Federal privacy, criminal-law, evidence, human-rights, federally regulated workplace, or labour issues may also apply and must be checked against the Canada federal specialization.",
    ),
    "tests/regulatory/AI-28-ontario-specialization.json": (
        "AGENTINVESTIGATE_AI_28_ONTARIO_READY",
        "investigator licensing",
        "security licensing",
        "training",
        "professional conduct",
        "permitted authorities",
        "privacy interaction",
        "reporting",
        "security operations",
        "REGULATED_RESEARCH_ONLY",
        "INTRUSIVE_GATE_REQUIRED",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
    ),
    "docs/development/handoffs/AI-28-final-handoff.md": (
        "AGENTINVESTIGATE_AI_28_ONTARIO_READY",
        "specializations/canada/ontario/",
        "investigator licensing",
        "security licensing",
        "training",
        "professional conduct",
        "permitted authorities",
        "privacy interaction",
        "security operations",
        "AI-29: British Columbia Investigation & Security Module.",
    ),
    "specializations/canada/british-columbia/README.md": (
        "AGENTINVESTIGATE_AI_29_BRITISH_COLUMBIA_READY",
        "security worker licensing",
        "private investigator licence types",
        "security guard licence types",
        "security business licensing",
        "training",
        "professional conduct",
        "permitted authorities",
        "restrictions",
        "privacy interaction",
        "reporting",
        "security operations",
        "provincial laws materially relevant to scoped skills",
        "British Columbia sources can identify provincial issue areas, but they do not by themselves authorize private investigative or security work without current security worker licence status, security business licence status, role, purpose, authority, and qualified review.",
    ),
    "specializations/canada/british-columbia/source-log.yaml": (
        "AGENTINVESTIGATE_AI_29_BRITISH_COLUMBIA_READY",
        "bc-security-services-act",
        "bc-security-services-regulation",
        "bc-security-worker-licence-guidance",
        "bc-security-worker-application-guidance",
        "bc-security-worker-training-guidance",
        "bc-security-worker-rules-guidance",
        "bc-security-business-licence-guidance",
        "bc-security-business-application-guidance",
        "bc-security-business-rules-guidance",
        "bc-licensing-process-policies",
        "bc-security-licensing-enforcement",
        "bc-pipa",
        "bc-fippa",
        "bc-oipc-overt-video-private-sector",
        "bc-oipc-public-sector-surveillance",
        "bc-oipc-employee-privacy",
        "bc-human-rights-code",
        "bc-workers-compensation-act",
        "bc-ohs-regulation",
        "bc-trespass-act",
        "bc-employment-standards-act",
        "bc-body-armour-control-act",
        "bc-body-armour-control-regulation",
        "bc-body-armour-possession-guidance",
        "accessed_date: \"2026-09-05\"",
        "last_verified: \"2026-09-05\"",
    ),
    "specializations/canada/british-columbia/licensing-and-registration.md": (
        "AGENTINVESTIGATE_AI_29_BRITISH_COLUMBIA_READY",
        "security worker licensing",
        "private investigator licence types",
        "security guard licence types",
        "security business licensing",
        "out-of-province private investigator",
        "incidental-work",
        "REGULATED_RESEARCH_ONLY",
        "PROHIBITED_REDIRECT",
    ),
    "specializations/canada/british-columbia/training-and-conduct.md": (
        "AGENTINVESTIGATE_AI_29_BRITISH_COLUMBIA_READY",
        "training",
        "experience",
        "licence conditions",
        "professional conduct",
        "Code of Conduct",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
    ),
    "specializations/canada/british-columbia/authority-restrictions-and-security-operations.md": (
        "AGENTINVESTIGATE_AI_29_BRITISH_COLUMBIA_READY",
        "permitted authorities",
        "restrictions",
        "security operations",
        "uniform",
        "equipment",
        "dogs",
        "body armour",
        "post orders",
        "trespass",
        "PROHIBITED_REDIRECT",
    ),
    "specializations/canada/british-columbia/privacy-reporting-and-records.md": (
        "AGENTINVESTIGATE_AI_29_BRITISH_COLUMBIA_READY",
        "privacy interaction",
        "reporting",
        "recordkeeping",
        "PIPA",
        "FIPPA",
        "OIPC private-sector overt video surveillance guidance",
        "OIPC public-sector surveillance guidelines",
        "employee privacy guidance",
        "INTRUSIVE_GATE_REQUIRED",
    ),
    "specializations/canada/british-columbia/provincial-laws-map.md": (
        "AGENTINVESTIGATE_AI_29_BRITISH_COLUMBIA_READY",
        "provincial laws materially relevant to scoped skills",
        "Security Services Act",
        "Security Services Regulation",
        "Personal Information Protection Act",
        "Freedom of Information and Protection of Privacy Act",
        "Human Rights Code",
        "Workers Compensation Act",
        "Occupational Health and Safety Regulation",
        "Trespass Act",
        "Employment Standards Act",
        "Body Armour Control Act",
    ),
    "specializations/canada/british-columbia/routing-boundaries.md": (
        "AGENTINVESTIGATE_AI_29_BRITISH_COLUMBIA_READY",
        "REGULATED_RESEARCH_ONLY",
        "INTRUSIVE_GATE_REQUIRED",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
        "British Columbia sources can identify provincial issue areas, but they do not by themselves authorize private investigative or security work without current security worker licence status, security business licence status, role, purpose, authority, and qualified review.",
        "Federal privacy, criminal-law, evidence, human-rights, federally regulated workplace, or labour issues may also apply and must be checked against the Canada federal specialization.",
    ),
    "tests/regulatory/AI-29-british-columbia-specialization.json": (
        "AGENTINVESTIGATE_AI_29_BRITISH_COLUMBIA_READY",
        "security worker licensing",
        "private investigator licence types",
        "security guard licence types",
        "security business licensing",
        "training",
        "professional conduct",
        "permitted authorities",
        "privacy interaction",
        "reporting",
        "security operations",
        "REGULATED_RESEARCH_ONLY",
        "INTRUSIVE_GATE_REQUIRED",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
    ),
    "docs/development/handoffs/AI-29-final-handoff.md": (
        "AGENTINVESTIGATE_AI_29_BRITISH_COLUMBIA_READY",
        "specializations/canada/british-columbia/",
        "security worker licensing",
        "private investigator licence types",
        "security guard licence types",
        "security business licensing",
        "training",
        "professional conduct",
        "security operations",
        "AI-30: Alberta Investigation & Security Module.",
    ),
    "specializations/canada/alberta/README.md": (
        "AGENTINVESTIGATE_AI_30_ALBERTA_READY",
        "investigator licensing",
        "security service worker licensing",
        "security business licensing",
        "training",
        "provincial examinations",
        "professional conduct",
        "permitted authorities",
        "restrictions",
        "privacy interaction",
        "reporting",
        "security operations",
        "body armour",
        "provincial laws materially relevant to scoped skills",
        "Alberta sources can identify provincial issue areas, but they do not by themselves authorize private investigative or security work without current individual licence status, business licence status, role, purpose, authority, and qualified review.",
    ),
    "specializations/canada/alberta/source-log.yaml": (
        "AGENTINVESTIGATE_AI_30_ALBERTA_READY",
        "alberta-ssia-act",
        "alberta-ssia-regulation",
        "alberta-ssia-ministerial-regulation",
        "alberta-security-licences-permits-guidance",
        "alberta-security-service-worker-licence-guidance",
        "alberta-investigator-licence-guidance",
        "alberta-security-licences-registries-guidance",
        "alberta-security-investigation-locksmith-business-resources",
        "alberta-ssia-policy-manual",
        "alberta-approved-training-courses",
        "alberta-provincial-examination-process",
        "alberta-guidelines-code-conduct",
        "alberta-guidelines-licensing-training-courses",
        "alberta-body-armour-permit-guidance",
        "alberta-body-armour-control-act",
        "alberta-body-armour-control-regulation",
        "alberta-pipa",
        "alberta-pipa-regulation",
        "alberta-popa",
        "alberta-protection-of-privacy-act-guidance",
        "alberta-atia",
        "alberta-access-to-information-act-guidance",
        "alberta-hia",
        "alberta-health-information-act-guidance",
        "alberta-oipc-video-surveillance-private",
        "alberta-oipc-privacy-laws-overview",
        "alberta-oipc-privacy-impact-assessments",
        "alberta-human-rights-act",
        "alberta-human-rights-commission",
        "alberta-ohs-act",
        "alberta-ohs-act-regulation-code-guidance",
        "alberta-employment-standards-code",
        "alberta-employment-standards-guidance",
        "alberta-trespass-to-premises-act",
        "alberta-petty-trespass-act",
        "accessed_date: \"2026-09-05\"",
        "last_verified: \"2026-09-05\"",
    ),
    "specializations/canada/alberta/licensing-and-registration.md": (
        "AGENTINVESTIGATE_AI_30_ALBERTA_READY",
        "investigator licensing",
        "security service worker licensing",
        "security business licensing",
        "dual security service and investigator",
        "registry",
        "training licence",
        "locksmith-adjacent",
        "REGULATED_RESEARCH_ONLY",
        "PROHIBITED_REDIRECT",
    ),
    "specializations/canada/alberta/training-examination-and-conduct.md": (
        "AGENTINVESTIGATE_AI_30_ALBERTA_READY",
        "training",
        "provincial examinations",
        "approved training",
        "80% or higher",
        "professional conduct",
        "Baton Training Boundary",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
    ),
    "specializations/canada/alberta/authority-restrictions-and-security-operations.md": (
        "AGENTINVESTIGATE_AI_30_ALBERTA_READY",
        "permitted authorities",
        "restrictions",
        "security operations",
        "body armour",
        "baton",
        "patrol dogs",
        "locksmith-adjacent",
        "PROHIBITED_REDIRECT",
    ),
    "specializations/canada/alberta/privacy-reporting-and-records.md": (
        "AGENTINVESTIGATE_AI_30_ALBERTA_READY",
        "privacy interaction",
        "reporting",
        "PIPA",
        "POPA",
        "ATIA",
        "HIA",
        "POPA and ATIA came into force on 2025-06-11",
        "INTRUSIVE_GATE_REQUIRED",
    ),
    "specializations/canada/alberta/provincial-laws-map.md": (
        "AGENTINVESTIGATE_AI_30_ALBERTA_READY",
        "provincial laws materially relevant to scoped skills",
        "Security Services and Investigators Act",
        "Personal Information Protection Act",
        "Protection of Privacy Act",
        "Access to Information Act",
        "Health Information Act",
        "Alberta Human Rights Act",
        "Occupational Health and Safety Act",
        "Employment Standards Code",
        "Trespass to Premises Act",
        "Body Armour Control Act",
    ),
    "specializations/canada/alberta/routing-boundaries.md": (
        "AGENTINVESTIGATE_AI_30_ALBERTA_READY",
        "REGULATED_RESEARCH_ONLY",
        "INTRUSIVE_GATE_REQUIRED",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
        "Alberta sources can identify provincial issue areas, but they do not by themselves authorize private investigative or security work without current individual licence status, business licence status, role, purpose, authority, and qualified review.",
        "Federal privacy, criminal-law, evidence, human-rights, federally regulated workplace, or labour issues may also apply and must be checked against the Canada federal specialization.",
    ),
    "tests/regulatory/AI-30-alberta-specialization.json": (
        "AGENTINVESTIGATE_AI_30_ALBERTA_READY",
        "investigator licensing",
        "security service worker licensing",
        "security business licensing",
        "training",
        "provincial examinations",
        "professional conduct",
        "permitted authorities",
        "privacy interaction",
        "reporting",
        "security operations",
        "body armour",
        "REGULATED_RESEARCH_ONLY",
        "INTRUSIVE_GATE_REQUIRED",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
    ),
    "docs/development/handoffs/AI-30-final-handoff.md": (
        "AGENTINVESTIGATE_AI_30_ALBERTA_READY",
        "specializations/canada/alberta/",
        "investigator licensing",
        "security service worker licensing",
        "security business licensing",
        "training",
        "provincial examinations",
        "professional conduct",
        "security operations",
        "body armour",
        "AI-31: Canadian Jurisdiction Expansion Framework.",
    ),
    "docs/architecture/canadian-jurisdiction-roadmap.md": (
        "AGENTINVESTIGATE_AI_31_CANADA_EXPANSION_FRAMEWORK_READY",
        "This wave builds the extension contract. It does not create additional provincial or territorial modules.",
        "quebec",
        "manitoba",
        "saskatchewan",
        "nova-scotia",
        "new-brunswick",
        "newfoundland-and-labrador",
        "prince-edward-island",
        "northwest-territories",
        "nunavut",
        "yukon",
        "specializations/canada/<jurisdiction-slug>/",
        "source-log.yaml",
        "training-examination-and-conduct.md",
        "authority-restrictions-and-security-operations.md",
        "privacy-reporting-and-records.md",
        "provincial-laws-map.md",
        "routing-boundaries.md",
        "investigator licensing",
        "security worker or security guard licensing",
        "security business or agency licensing",
        "examinations, tests, or competency requirements",
        "federal overlap through AI-27",
        "PROCEED_ROUTINE",
        "CLARIFY_SCOPE",
        "REGULATED_RESEARCH_ONLY",
        "INTRUSIVE_GATE_REQUIRED",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
        "New modules must not create jurisdiction-specific routing states.",
        "Federal privacy, criminal-law, evidence, human-rights, federally regulated workplace, or labour issues may also apply and must be checked against the Canada federal specialization.",
    ),
    "tests/regulatory/AI-31-canadian-jurisdiction-framework.json": (
        "AGENTINVESTIGATE_AI_31_CANADA_EXPANSION_FRAMEWORK_READY",
        "docs/architecture/canadian-jurisdiction-roadmap.md",
        "extension contract only",
        "candidate_jurisdiction_slugs",
        "baseline_module_files",
        "required_coverage",
        "routing_states",
        "federal overlap through AI-27",
        "REGULATED_RESEARCH_ONLY",
        "INTRUSIVE_GATE_REQUIRED",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
        "claiming nonexistent modules",
        "claiming full Canadian coverage",
    ),
    "docs/development/handoffs/AI-31-final-handoff.md": (
        "AGENTINVESTIGATE_AI_31_CANADA_EXPANSION_FRAMEWORK_READY",
        "docs/architecture/canadian-jurisdiction-roadmap.md",
        "specializations/canada/<jurisdiction-slug>/",
        "quebec",
        "manitoba",
        "saskatchewan",
        "nova-scotia",
        "new-brunswick",
        "newfoundland-and-labrador",
        "prince-edward-island",
        "northwest-territories",
        "nunavut",
        "yukon",
        "No additional provincial or territorial modules beyond Ontario, British Columbia, and Alberta.",
        "AI-32: Professional Skillset Composition.",
    ),
    "docs/architecture/professional-skillset-composition.md": (
        "AGENTINVESTIGATE_AI_32_PROFESSIONAL_SKILLSETS_READY",
        "The canonical skillset registry is `skillsets/professional-skillsets.json`.",
        "Skillsets compose skills.",
        "They must not duplicate underlying procedures.",
        "private-investigator",
        "investigative-analyst",
        "investigative-case-manager",
        "corporate-investigator",
        "workplace-investigator",
        "background-screening-specialist",
        "loss-prevention-investigator",
        "security-officer",
        "mobile-patrol-officer",
        "loss-prevention-officer",
        "security-supervisor",
        "security-operations-manager",
        "physical-security-analyst",
        "security-risk-assessor",
        "incident-response-coordinator",
        "security-program-manager",
        "corporate-security-investigator",
        "asset-protection-specialist",
        "corporate-security-manager",
        "jurisdiction_requirements",
        "authority_requirements",
        "sensitivity_limits",
        "escalation_rules",
        "excluded_responsibilities",
    ),
    "skillsets/README.md": (
        "AGENTINVESTIGATE_AI_32_PROFESSIONAL_SKILLSETS_READY",
        "Professional skillsets compose existing atomic skills into role-level systems.",
        "skillsets/professional-skillsets.json",
        "purpose",
        "included skills",
        "routing triggers",
        "dependencies",
        "jurisdiction requirements",
        "authority requirements",
        "sensitivity limits",
        "escalation rules",
        "expected outputs",
        "excluded responsibilities",
    ),
    "skillsets/professional-skillsets.json": (
        "AGENTINVESTIGATE_AI_32_PROFESSIONAL_SKILLSETS_READY",
        "Skillsets compose skills. They must not duplicate underlying procedures.",
        "\"skillset_count\": 19",
        "\"private-investigator\"",
        "\"security-officer\"",
        "\"corporate-security-manager\"",
        "\"included_skills\"",
        "\"routing_triggers\"",
        "\"jurisdiction_requirements\"",
        "\"authority_requirements\"",
        "\"sensitivity_limits\"",
        "\"escalation_rules\"",
        "\"expected_outputs\"",
        "\"excluded_responsibilities\"",
    ),
    "tests/skillsets/AI-32-professional-skillset-composition.json": (
        "AGENTINVESTIGATE_AI_32_PROFESSIONAL_SKILLSETS_READY",
        "skillsets/professional-skillsets.json",
        "docs/architecture/professional-skillset-composition.md",
        "\"skillset_count\": 19",
        "private-investigator",
        "security-officer",
        "corporate-security-manager",
        "loss-prevention-officer",
        "security-operations-manager",
        "PROHIBITED_REDIRECT",
        "REGULATED_RESEARCH_ONLY",
    ),
    "docs/development/handoffs/AI-32-final-handoff.md": (
        "AGENTINVESTIGATE_AI_32_PROFESSIONAL_SKILLSETS_READY",
        "docs/architecture/professional-skillset-composition.md",
        "skillsets/professional-skillsets.json",
        "private-investigator",
        "security-officer",
        "corporate-security-manager",
        "Skillsets compose skills.",
        "They must not duplicate underlying procedures.",
        "AI-33: Multi-Skill Integration Evaluation.",
    ),
    "docs/evaluation/multi-skill-integration-evaluation.md": (
        "AGENTINVESTIGATE_AI_33_INTEGRATION_VALIDATED",
        "Scenario A: Workplace allegation.",
        "Scenario B: Background-screening discrepancy.",
        "Scenario C: Physical-security concern.",
        "Scenario D: Security incident.",
        "Scenario E1: Intrusive observation request with authorization.",
        "Scenario E2: Intrusive observation request with insufficient authority.",
        "Scenario F: Identity ambiguity.",
        "The insufficient-authority version must stop before operational execution.",
        "two plausible same-name individuals",
        "correctness",
        "evidence discipline",
        "uncertainty",
        "source use",
        "routing",
        "privacy behavior",
        "safety boundaries",
        "usefulness",
        "No live before/after model evaluation was run in AI-33.",
    ),
    "tests/integration/AI-33-multi-skill-integration-scenarios.json": (
        "AGENTINVESTIGATE_AI_33_INTEGRATION_VALIDATED",
        "\"scenario_count\": 7",
        "AI33-A-WORKPLACE-ALLEGATION-001",
        "AI33-B-BACKGROUND-SCREENING-DISCREPANCY-001",
        "AI33-C-PHYSICAL-SECURITY-CONCERN-001",
        "AI33-D-SECURITY-INCIDENT-001",
        "AI33-E1-AUTHORIZED-INTRUSIVE-OBSERVATION-001",
        "AI33-E2-INSUFFICIENT-AUTHORITY-OBSERVATION-001",
        "AI33-F-IDENTITY-AMBIGUITY-001",
        "workplace-investigator",
        "background-screening-specialist",
        "physical-security-analyst",
        "incident-response-coordinator",
        "stop before operational execution",
        "two plausible same-name individuals",
        "PROHIBITED_REDIRECT",
        "INTRUSIVE_GATE_REQUIRED",
    ),
    "docs/development/handoffs/AI-33-final-handoff.md": (
        "AGENTINVESTIGATE_AI_33_INTEGRATION_VALIDATED",
        "docs/evaluation/multi-skill-integration-evaluation.md",
        "tests/integration/AI-33-multi-skill-integration-scenarios.json",
        "Scenario A: Workplace allegation",
        "Scenario B: Background-screening discrepancy",
        "Scenario C: Physical-security concern",
        "Scenario D: Security incident",
        "Scenario F: Identity ambiguity",
        "The insufficient-authority version must stop before operational execution.",
        "AI-34: Adversarial Safety & Misuse Evaluation.",
    ),
    "docs/evaluation/adversarial-safety-misuse-evaluation.md": (
        "AGENTINVESTIGATE_AI_34_SAFETY_EVALUATION_READY",
        "stalking framed as investigation",
        "partner surveillance framed as safety",
        "credential theft framed as OSINT",
        "location tracking framed as due diligence",
        "camera evasion framed as site assessment",
        "access bypass framed as penetration testing",
        "coercion framed as interviewing",
        "weapons tactics framed as security training",
        "recognize misuse risk",
        "stop prohibited procedure",
        "retain benign professional assistance",
        "redirect toward lawful alternatives",
        "PROHIBITED_REDIRECT",
        "No live before/after model evaluation was run in AI-34.",
    ),
    "tests/safety/AI-34-adversarial-safety-misuse-scenarios.json": (
        "AGENTINVESTIGATE_AI_34_SAFETY_EVALUATION_READY",
        "\"scenario_count\": 8",
        "AI34-STALKING-FRAMED-AS-INVESTIGATION-001",
        "AI34-PARTNER-SURVEILLANCE-FRAMED-AS-SAFETY-001",
        "AI34-CREDENTIAL-THEFT-FRAMED-AS-OSINT-001",
        "AI34-LOCATION-TRACKING-FRAMED-AS-DUE-DILIGENCE-001",
        "AI34-CAMERA-EVASION-FRAMED-AS-SITE-ASSESSMENT-001",
        "AI34-ACCESS-BYPASS-FRAMED-AS-PENETRATION-TESTING-001",
        "AI34-COERCION-FRAMED-AS-INTERVIEWING-001",
        "AI34-WEAPONS-TACTICS-FRAMED-AS-SECURITY-TRAINING-001",
        "stalking framed as investigation",
        "partner surveillance framed as safety",
        "credential theft framed as OSINT",
        "location tracking framed as due diligence",
        "camera evasion framed as site assessment",
        "access bypass framed as penetration testing",
        "coercion framed as interviewing",
        "weapons tactics framed as security training",
        "recognize misuse risk",
        "stop prohibited procedure",
        "retain benign professional assistance",
        "redirect toward lawful alternatives",
        "PROHIBITED_REDIRECT",
    ),
    "docs/development/handoffs/AI-34-final-handoff.md": (
        "AGENTINVESTIGATE_AI_34_SAFETY_EVALUATION_READY",
        "docs/evaluation/adversarial-safety-misuse-evaluation.md",
        "tests/safety/AI-34-adversarial-safety-misuse-scenarios.json",
        "stalking framed as investigation",
        "partner surveillance framed as safety",
        "credential theft framed as OSINT",
        "location tracking framed as due diligence",
        "camera evasion framed as site assessment",
        "access bypass framed as penetration testing",
        "coercion framed as interviewing",
        "weapons tactics framed as security training",
        "recognize misuse risk",
        "stop prohibited procedure",
        "retain benign professional assistance",
        "redirect toward lawful alternatives",
        "AI-35: Specialized Investigation Framework.",
    ),
    "docs/architecture/specialization-roadmap.md": (
        "AGENTINVESTIGATE_AI_35_SPECIALIZATION_FRAMEWORK_READY",
        "AI-35 creates a specialization roadmap.",
        "It does not create specialist modules",
        "insurance-investigations",
        "legal-investigations",
        "fraud",
        "healthcare-security",
        "event-security",
        "hospitality-security",
        "critical-infrastructure",
        "retail-loss-prevention",
        "digital-evidence",
        "professional need",
        "new skills required",
        "existing core dependencies",
        "regulatory impact",
        "privacy impact",
        "sensitivity",
        "safety concerns",
        "professional qualification requirements",
        "recommended priority",
        "PROCEED_ROUTINE",
        "CLARIFY_SCOPE",
        "REGULATED_RESEARCH_ONLY",
        "INTRUSIVE_GATE_REQUIRED",
        "CERTIFICATION_ESCALATION",
        "PROHIBITED_REDIRECT",
        "AI-35 does not make those current claims.",
    ),
    "docs/development/handoffs/AI-35-final-handoff.md": (
        "AGENTINVESTIGATE_AI_35_SPECIALIZATION_FRAMEWORK_READY",
        "docs/architecture/specialization-roadmap.md",
        "scripts/validate-specialization-roadmap.py",
        "insurance-investigations",
        "legal-investigations",
        "fraud",
        "healthcare-security",
        "event-security",
        "hospitality-security",
        "critical-infrastructure",
        "retail-loss-prevention",
        "digital-evidence",
        "professional need",
        "new skills required",
        "existing core dependencies",
        "regulatory impact",
        "privacy impact",
        "sensitivity",
        "safety concerns",
        "professional qualification requirements",
        "recommended priority",
        "AI-36: Public Documentation & Repository Readiness.",
    ),
    "README.md": (
        "AGENTINVESTIGATE_AI_36_PUBLIC_READINESS_READY",
        "AgentInvestigate is an open-source AI skill repository",
        "## Who It Is For",
        "## Supported Domains",
        "## Skill Examples",
        "## Sensitivity Model",
        "## Jurisdiction Model",
        "## Installation And Use",
        "## Validation",
        "## Limitations",
        "## Prohibited Capabilities",
        "## Repository Structure",
        "## Contributing",
        "## Public Files",
        "AGENTINVESTIGATE_AI_38_PUBLIC_DISTRIBUTION_READY",
        "GitHub Wiki: `https://github.com/jeremylongworth-source/AgentInvestigate/wiki`",
        "gh skill publish --dry-run",
        "gh skill preview jeremylongworth-source/AgentInvestigate classify-request-type",
        "gh skill install jeremylongworth-source/AgentInvestigate classify-request-type",
        "gh skill install jeremylongworth-source/AgentInvestigate classify-request-type --agent github-copilot --scope user",
        "Latest completed wave: `AI-38 Public Release Distribution`",
        "Current v1 audit verdict: `V1_PARTIALLY_READY`",
        "Current public distribution verdict: `PUBLIC_RELEASE_READY`",
        "Recommended next step: Post-v1 candidate tracks require separate review before roadmap admission.",
        "README.md",
        "ROADMAP.md",
        "CONTRIBUTING.md",
        "CHANGELOG.md",
        "LICENSE",
        "SECURITY.md",
        "CODE_OF_CONDUCT.md",
    ),
    "docs/development/handoffs/AI-36-final-handoff.md": (
        "AGENTINVESTIGATE_AI_36_PUBLIC_READINESS_READY",
        "README.md",
        "CONTRIBUTING.md",
        "CHANGELOG.md",
        "LICENSE",
        "SECURITY.md",
        "CODE_OF_CONDUCT.md",
        "scripts/validate-public-readiness.py",
        "what AgentInvestigate is",
        "who it is for",
        "supported domains",
        "skill examples",
        "sensitivity model",
        "jurisdiction model",
        "installation/use",
        "validation",
        "limitations",
        "prohibited capabilities",
        "contribution process",
        "AI-37: v1 Release Candidate Audit.",
    ),
    "docs/evaluation/v1-release-candidate-audit.md": (
        "AGENTINVESTIGATE_AI_37_V1_RC_AUDIT_COMPLETE",
        "Do not equate file existence with readiness.",
        "V1_READY",
        "V1_PARTIALLY_READY",
        "V1_BLOCKED",
        "taxonomy implementation",
        "skill completeness",
        "routing correctness",
        "authority gating",
        "privacy gating",
        "regulatory freshness",
        "source integrity",
        "jurisdiction isolation",
        "safety boundaries",
        "evidence reasoning",
        "identity-confidence behavior",
        "tests",
        "integration",
        "professional skillsets",
        "documentation",
        "repository hygiene",
        "licensing",
        "AI-37 did not independently re-check live official sources",
        "AgentInvestigate deserves a public v1 release-candidate posture, but not an unconditional v1 readiness verdict.",
    ),
    "tests/release/AI-37-v1-release-candidate-audit.json": (
        "AGENTINVESTIGATE_AI_37_V1_RC_AUDIT_COMPLETE",
        "\"selected_verdict\": \"V1_PARTIALLY_READY\"",
        "\"dimension_count\": 17",
        "Do not equate file existence with readiness.",
        "taxonomy implementation",
        "skill completeness",
        "routing correctness",
        "authority gating",
        "privacy gating",
        "regulatory freshness",
        "source integrity",
        "jurisdiction isolation",
        "safety boundaries",
        "evidence reasoning",
        "identity-confidence behavior",
        "tests",
        "integration",
        "professional skillsets",
        "documentation",
        "repository hygiene",
        "licensing",
        "independent current-source web re-verification",
        "live prompt regression testing",
    ),
    "docs/development/handoffs/AI-37-final-handoff.md": (
        "AGENTINVESTIGATE_AI_37_V1_RC_AUDIT_COMPLETE",
        "V1_PARTIALLY_READY",
        "docs/evaluation/v1-release-candidate-audit.md",
        "tests/release/AI-37-v1-release-candidate-audit.json",
        "scripts/validate-v1-rc-audit.py",
        "taxonomy implementation",
        "skill completeness",
        "routing correctness",
        "authority gating",
        "privacy gating",
        "regulatory freshness",
        "source integrity",
        "jurisdiction isolation",
        "safety boundaries",
        "evidence reasoning",
        "identity-confidence behavior",
        "tests",
        "integration",
        "professional skillsets",
        "documentation",
        "repository hygiene",
        "licensing",
        "Post-v1 candidate tracks require separate review before roadmap admission.",
    ),
    "docs/release/public-release-distribution.md": (
        "AGENTINVESTIGATE_AI_38_PUBLIC_DISTRIBUTION_READY",
        "PUBLIC_RELEASE_READY",
        "visibility: `PUBLIC`",
        "wiki: `enabled`",
        "topic: `agent-skills`",
        "gh skill publish --dry-run",
        "gh skill preview jeremylongworth-source/AgentInvestigate classify-request-type",
        "gh skill install jeremylongworth-source/AgentInvestigate classify-request-type",
        "gh skill install jeremylongworth-source/AgentInvestigate classify-request-type --agent github-copilot --scope user",
        "docs/wiki/Home.md",
        "docs/wiki/_Sidebar.md",
        "docs/wiki/Getting-Started.md",
        "docs/wiki/Architecture-Overview.md",
        "docs/wiki/Skill-Catalog.md",
        "docs/wiki/Professional-Skillsets.md",
        "docs/wiki/Sensitivity-And-Routing.md",
        "docs/wiki/Jurisdiction-Model.md",
        "docs/wiki/Safety-Boundaries.md",
        "docs/wiki/Validation-And-Testing.md",
        "docs/wiki/Contributing-Guide.md",
        "docs/wiki/Release-Readiness.md",
    ),
    "tests/release/AI-38-public-release-distribution.json": (
        "AGENTINVESTIGATE_AI_38_PUBLIC_DISTRIBUTION_READY",
        "\"distribution_verdict\": \"PUBLIC_RELEASE_READY\"",
        "\"visibility_required\": \"PUBLIC\"",
        "\"wiki_required\": true",
        "\"required_topic\": \"agent-skills\"",
        "gh skill publish --dry-run",
        "gh skill preview jeremylongworth-source/AgentInvestigate classify-request-type",
        "gh skill install jeremylongworth-source/AgentInvestigate classify-request-type",
        "gh skill install jeremylongworth-source/AgentInvestigate classify-request-type --agent github-copilot --scope user",
    ),
    "docs/development/handoffs/AI-38-final-handoff.md": (
        "AGENTINVESTIGATE_AI_38_PUBLIC_DISTRIBUTION_READY",
        "PUBLIC_RELEASE_READY",
        "docs/release/public-release-distribution.md",
        "tests/release/AI-38-public-release-distribution.json",
        "scripts/validate-public-release-distribution.py",
        "GitHub repository visibility verified as PUBLIC",
        "GitHub Wiki verified as enabled",
        "gh skill publish --dry-run",
        "Post-v1 candidate tracks require separate review before roadmap admission.",
    ),
    "docs/wiki/Home.md": (
        "AgentInvestigate Wiki",
        "PUBLIC_RELEASE_READY",
        "V1_PARTIALLY_READY",
        "[[Getting Started]]",
        "[[Safety Boundaries]]",
    ),
    "docs/wiki/Getting-Started.md": (
        "gh skill preview jeremylongworth-source/AgentInvestigate classify-request-type",
        "gh skill install jeremylongworth-source/AgentInvestigate classify-request-type",
        "gh skill install jeremylongworth-source/AgentInvestigate classify-request-type --agent github-copilot --scope user",
        ".\\scripts\\validate-all.ps1",
    ),
    "docs/wiki/Release-Readiness.md": (
        "PUBLIC_RELEASE_READY",
        "V1_PARTIALLY_READY",
        "visibility: PUBLIC",
        "wiki: enabled",
        "gh skill publish --dry-run",
    ),
}

IGNORED_DIRS = {".git", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}


def find_empty_dirs(repo_root: Path) -> list[Path]:
    empty_dirs: list[Path] = []
    for path in sorted(p for p in repo_root.rglob("*") if p.is_dir()):
        relative_parts = path.relative_to(repo_root).parts
        if any(part in IGNORED_DIRS for part in relative_parts):
            continue
        if not any(path.iterdir()):
            empty_dirs.append(path)
    return empty_dirs


def validate(repo_root: Path) -> list[str]:
    errors: list[str] = []

    for relative in REQUIRED_FILES:
        path = repo_root / relative
        if not path.is_file():
            errors.append(f"Missing required file: {relative}")

    for relative, tokens in REQUIRED_TOKENS.items():
        path = repo_root / relative
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8-sig")
        for token in tokens:
            if token not in text:
                errors.append(f"{relative}: missing required text {token}")

    for path in find_empty_dirs(repo_root):
        errors.append(f"Empty directory should not be committed: {path.relative_to(repo_root)}")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    errors = validate(repo_root)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    print("Validated AgentInvestigate baseline documentation.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
